// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package historydb

type AddressEvent struct {
	ID                string
	PublicAddressID   string
	SourcePathID      string
	NodeID            string
	HistoryGeneration string
	Sequence          int64
	Kind              string
	Family            string
	PublicAddress     *string
	LocalInterface    *string
	LocalAddress      *string
	ProxyPath         int64
	LikelyNat         int64
	Temporary         int64
	FailureReason     *string
	ObservedAt        int64
	ReceivedAt        int64
}

type AddressState struct {
	EgressID          string
	NodeID            string
	HistoryGeneration string
	Family            string
	Status            string
	Sequence          int64
	PublicAddress     *string
	LocalInterface    *string
	LocalAddress      *string
	ProxyPath         int64
	LikelyNat         int64
	Temporary         int64
	FailureReason     *string
	LastCheckedAt     int64
	LastSucceededAt   *int64
	LastChangedAt     *int64
	ReceivedAt        int64
}

type CurrentProbeSnapshot struct {
	EgressID    string
	ExecutionID string
	SnapshotID  string
	Sequence    int64
	ObservedAt  int64
	ReceivedAt  int64
}

type HistoryGap struct {
	ID                string
	EgressID          string
	NodeID            string
	HistoryGeneration string
	Kind              string
	DroppedCount      int64
	FirstSequence     int64
	LastSequence      int64
	FirstObservedAt   int64
	LastObservedAt    int64
	ReceivedAt        int64
}

type HistoryMetadatum struct {
	ID         int64
	Generation string
	CreatedAt  int64
}

type NotificationDelivery struct {
	ID                 string
	EventID            string
	SenderID           string
	SenderName         string
	SenderKind         string
	EventType          string
	NodeID             *string
	EgressID           *string
	IsTest             int64
	Status             string
	AttemptCount       int64
	NextAttemptAt      *int64
	LastAttemptAt      *int64
	CompletedAt        *int64
	ErrorCode          *string
	MatchedRuleIdsJson []byte
	EventJson          []byte
	Title              string
	Body               string
	CreatedAt          int64
	UpdatedAt          int64
}

type NotificationEvent struct {
	ID          string
	EventType   string
	SourceKind  string
	SourceID    string
	NodeID      *string
	EgressID    *string
	PayloadJson []byte
	ObservedAt  int64
	RecordedAt  int64
	ProcessedAt *int64
}

type ProbeChangeSet struct {
	ID                 string
	ExecutionID        string
	SnapshotID         string
	EgressID           string
	Sequence           int64
	PreviousSnapshotID *string
	Baseline           int64
	ChangeCount        int64
	ObservedAt         int64
	RecordedAt         int64
}

type ProbeComparisonProgress struct {
	EgressID              string
	NodeID                string
	HistoryGeneration     string
	NextSequence          int64
	LastSuccessSnapshotID *string
	UpdatedAt             int64
}

type ProbeExecution struct {
	ID           string
	RunID        string
	EgressID     string
	Ordinal      int64
	Sequence     int64
	Status       string
	StartedAt    *int64
	CompletedAt  *int64
	FailureStage *string
	Diagnostic   *string
	ReceivedAt   int64
}

type ProbeFieldChange struct {
	ChangeSetID string
	FieldID     string
	GroupName   string
	JsonPath    string
	ValueType   string
	BeforeValue string
	AfterValue  string
}

type ProbeFormatEvent struct {
	ID                string
	ExecutionID       string
	SnapshotID        string
	EgressID          string
	Sequence          int64
	Kind              string
	PreviousSignature *string
	CurrentSignature  string
	IssueCount        int64
	IssuesJson        []byte
	ObservedAt        int64
	RecordedAt        int64
}

type ProbeFormatState struct {
	EgressID        string
	SnapshotID      string
	Sequence        int64
	Status          string
	Signature       string
	IssueCount      int64
	IssuesJson      []byte
	FirstObservedAt int64
	LastObservedAt  int64
	UpdatedAt       int64
}

type ProbeGap struct {
	ID                string
	EgressID          string
	NodeID            string
	HistoryGeneration string
	DroppedCount      int64
	FirstSequence     int64
	LastSequence      int64
	FirstObservedAt   int64
	LastObservedAt    int64
	ReceivedAt        int64
}

type ProbeOutcomeState struct {
	EgressID          string
	NodeID            string
	HistoryGeneration string
	ExecutionID       string
	Sequence          int64
	Status            string
	FirstObservedAt   int64
	LastObservedAt    int64
	UpdatedAt         int64
}

type ProbeRun struct {
	ID                    string
	NodeID                string
	HistoryGeneration     string
	ConfigurationRevision int64
	Trigger               string
	TaskID                *string
	Status                string
	ExpectedExecutions    int64
	StartedAt             int64
	CompletedAt           *int64
	ReceivedAt            int64
}

type ProbeSnapshot struct {
	ID          string
	ExecutionID string
	EgressID    string
	Sequence    int64
	ObservedAt  int64
	RawResult   []byte
	EncodedSize int64
	ReceivedAt  int64
}

type ProbeSnapshotFormat struct {
	SnapshotID string
	Status     string
	Signature  string
	IssueCount int64
	IssuesJson []byte
}

type ProbeSnapshotStar struct {
	SnapshotID string
	StarredAt  int64
}
