// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package historydb

import (
	"context"
)

const claimNotificationDelivery = `-- name: ClaimNotificationDelivery :execrows
UPDATE notification_deliveries
SET status = 'running', attempt_count = attempt_count + 1,
    next_attempt_at = NULL, last_attempt_at = ?, updated_at = ?
WHERE id = ?
  AND status IN ('pending', 'retrying')
  AND next_attempt_at <= ?
  AND attempt_count < 4
`

type ClaimNotificationDeliveryParams struct {
	LastAttemptAt *int64
	UpdatedAt     int64
	ID            string
	NextAttemptAt *int64
}

func (q *Queries) ClaimNotificationDelivery(ctx context.Context, arg ClaimNotificationDeliveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimNotificationDelivery,
		arg.LastAttemptAt,
		arg.UpdatedAt,
		arg.ID,
		arg.NextAttemptAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeNotificationDelivery = `-- name: CompleteNotificationDelivery :execrows
UPDATE notification_deliveries
SET status = 'succeeded', completed_at = ?, error_code = NULL, updated_at = ?
WHERE id = ? AND status = 'running'
`

type CompleteNotificationDeliveryParams struct {
	CompletedAt *int64
	UpdatedAt   int64
	ID          string
}

func (q *Queries) CompleteNotificationDelivery(ctx context.Context, arg CompleteNotificationDeliveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeNotificationDelivery, arg.CompletedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeProbeRun = `-- name: CompleteProbeRun :execrows
UPDATE probe_runs
SET status = ?, completed_at = ?, received_at = ?
WHERE id = ? AND status = 'running'
`

type CompleteProbeRunParams struct {
	Status      string
	CompletedAt *int64
	ReceivedAt  int64
	ID          string
}

func (q *Queries) CompleteProbeRun(ctx context.Context, arg CompleteProbeRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeProbeRun,
		arg.Status,
		arg.CompletedAt,
		arg.ReceivedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countActiveNotificationDeliveriesForSender = `-- name: CountActiveNotificationDeliveriesForSender :one
SELECT COUNT(*)
FROM notification_deliveries
WHERE sender_id = ? AND status IN ('pending', 'running', 'retrying')
`

func (q *Queries) CountActiveNotificationDeliveriesForSender(ctx context.Context, senderID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveNotificationDeliveriesForSender, senderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGlobalAddressEvents = `-- name: CountGlobalAddressEvents :one
SELECT COUNT(*) FROM address_events
WHERE (?1 = '' OR node_id = ?1)
  AND (?2 = '' OR public_address_id = ?2)
  AND (?3 IS NULL OR observed_at >= ?3)
  AND (?4 IS NULL OR observed_at <= ?4)
  AND (?5 = '' OR kind = ?5)
  AND (?6 = '' OR family = ?6)
`

type CountGlobalAddressEventsParams struct {
	NodeID         interface{}
	EgressID       interface{}
	FromObservedAt interface{}
	ToObservedAt   interface{}
	EventKind      interface{}
	Family         interface{}
}

func (q *Queries) CountGlobalAddressEvents(ctx context.Context, arg CountGlobalAddressEventsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGlobalAddressEvents,
		arg.NodeID,
		arg.EgressID,
		arg.FromObservedAt,
		arg.ToObservedAt,
		arg.EventKind,
		arg.Family,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGlobalAddressGaps = `-- name: CountGlobalAddressGaps :one
SELECT COUNT(*) FROM history_gaps
WHERE (?1 = '' OR node_id = ?1)
  AND (?2 = '' OR egress_id = ?2)
  AND (?3 IS NULL OR last_observed_at >= ?3)
  AND (?4 IS NULL OR last_observed_at <= ?4)
`

type CountGlobalAddressGapsParams struct {
	NodeID         interface{}
	EgressID       interface{}
	FromObservedAt interface{}
	ToObservedAt   interface{}
}

func (q *Queries) CountGlobalAddressGaps(ctx context.Context, arg CountGlobalAddressGapsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGlobalAddressGaps,
		arg.NodeID,
		arg.EgressID,
		arg.FromObservedAt,
		arg.ToObservedAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGlobalFormatEvents = `-- name: CountGlobalFormatEvents :one
SELECT COUNT(*)
FROM probe_format_events f
JOIN probe_executions e ON e.id = f.execution_id
JOIN probe_runs r ON r.id = e.run_id
WHERE (?1 = '' OR r.node_id = ?1)
  AND (?2 = '' OR f.egress_id = ?2)
  AND (?3 IS NULL OR f.observed_at >= ?3)
  AND (?4 IS NULL OR f.observed_at <= ?4)
`

type CountGlobalFormatEventsParams struct {
	NodeID         interface{}
	EgressID       interface{}
	FromObservedAt interface{}
	ToObservedAt   interface{}
}

func (q *Queries) CountGlobalFormatEvents(ctx context.Context, arg CountGlobalFormatEventsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGlobalFormatEvents,
		arg.NodeID,
		arg.EgressID,
		arg.FromObservedAt,
		arg.ToObservedAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGlobalProbeGaps = `-- name: CountGlobalProbeGaps :one
SELECT COUNT(*) FROM probe_gaps
WHERE (?1 = '' OR node_id = ?1)
  AND (?2 = '' OR egress_id = ?2)
  AND (?3 IS NULL OR last_observed_at >= ?3)
  AND (?4 IS NULL OR last_observed_at <= ?4)
`

type CountGlobalProbeGapsParams struct {
	NodeID         interface{}
	EgressID       interface{}
	FromObservedAt interface{}
	ToObservedAt   interface{}
}

func (q *Queries) CountGlobalProbeGaps(ctx context.Context, arg CountGlobalProbeGapsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGlobalProbeGaps,
		arg.NodeID,
		arg.EgressID,
		arg.FromObservedAt,
		arg.ToObservedAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNotificationDeliveries = `-- name: CountNotificationDeliveries :one
SELECT COUNT(*)
FROM notification_deliveries
WHERE (?1 = '' OR sender_id = ?1)
  AND (?2 = '' OR status = ?2)
`

type CountNotificationDeliveriesParams struct {
	SenderID       interface{}
	DeliveryStatus interface{}
}

func (q *Queries) CountNotificationDeliveries(ctx context.Context, arg CountNotificationDeliveriesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNotificationDeliveries, arg.SenderID, arg.DeliveryStatus)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProbeSnapshots = `-- name: CountProbeSnapshots :one
SELECT COUNT(*)
FROM probe_snapshots s
JOIN probe_executions e ON e.id = s.execution_id
JOIN probe_runs r ON r.id = e.run_id
LEFT JOIN probe_change_sets changes ON changes.snapshot_id = s.id
LEFT JOIN probe_snapshot_formats format ON format.snapshot_id = s.id
WHERE (?1 = '' OR r.node_id = ?1)
  AND (?2 = '' OR s.egress_id = ?2)
  AND (?3 IS NULL OR s.observed_at >= ?3)
  AND (?4 IS NULL OR s.observed_at <= ?4)
  AND (?5 = '' OR r.status = ?5)
  AND (?6 = '' OR r.trigger = ?6)
  AND (
      ?7 IS NULL OR
      (COALESCE(changes.change_count, 0) > 0) = ?7
  )
  AND (
      ?8 = '' OR
      COALESCE(format.status, 'mismatch') = ?8
  )
`

type CountProbeSnapshotsParams struct {
	NodeID         interface{}
	EgressID       interface{}
	FromObservedAt interface{}
	ToObservedAt   interface{}
	RunStatus      interface{}
	Trigger        interface{}
	Changed        interface{}
	FormatStatus   interface{}
}

func (q *Queries) CountProbeSnapshots(ctx context.Context, arg CountProbeSnapshotsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countProbeSnapshots,
		arg.NodeID,
		arg.EgressID,
		arg.FromObservedAt,
		arg.ToObservedAt,
		arg.RunStatus,
		arg.Trigger,
		arg.Changed,
		arg.FormatStatus,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAddressEvent = `-- name: CreateAddressEvent :execrows
INSERT INTO address_events (
    id, public_address_id, source_path_id, node_id, history_generation, sequence, kind, family,
    public_address, local_interface, local_address,
    proxy_path, likely_nat, temporary, failure_reason, observed_at, received_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type CreateAddressEventParams struct {
	ID                string
	PublicAddressID   string
	SourcePathID      string
	NodeID            string
	HistoryGeneration string
	Sequence          int64
	Kind              string
	Family            string
	PublicAddress     *string
	LocalInterface    *string
	LocalAddress      *string
	ProxyPath         int64
	LikelyNat         int64
	Temporary         int64
	FailureReason     *string
	ObservedAt        int64
	ReceivedAt        int64
}

func (q *Queries) CreateAddressEvent(ctx context.Context, arg CreateAddressEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAddressEvent,
		arg.ID,
		arg.PublicAddressID,
		arg.SourcePathID,
		arg.NodeID,
		arg.HistoryGeneration,
		arg.Sequence,
		arg.Kind,
		arg.Family,
		arg.PublicAddress,
		arg.LocalInterface,
		arg.LocalAddress,
		arg.ProxyPath,
		arg.LikelyNat,
		arg.Temporary,
		arg.FailureReason,
		arg.ObservedAt,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createHistoryMetadata = `-- name: CreateHistoryMetadata :exec
INSERT INTO history_metadata (id, generation, created_at)
VALUES (1, ?, ?)
`

type CreateHistoryMetadataParams struct {
	Generation string
	CreatedAt  int64
}

func (q *Queries) CreateHistoryMetadata(ctx context.Context, arg CreateHistoryMetadataParams) error {
	_, err := q.db.ExecContext(ctx, createHistoryMetadata, arg.Generation, arg.CreatedAt)
	return err
}

const createNotificationDelivery = `-- name: CreateNotificationDelivery :execrows
INSERT INTO notification_deliveries (
    id, event_id, sender_id, sender_name, sender_kind, event_type,
    node_id, egress_id, is_test, status, attempt_count, next_attempt_at,
    last_attempt_at, completed_at, error_code, matched_rule_ids_json,
    event_json, title, body, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (event_id, sender_id) DO NOTHING
`

type CreateNotificationDeliveryParams struct {
	ID                 string
	EventID            string
	SenderID           string
	SenderName         string
	SenderKind         string
	EventType          string
	NodeID             *string
	EgressID           *string
	IsTest             int64
	Status             string
	AttemptCount       int64
	NextAttemptAt      *int64
	LastAttemptAt      *int64
	CompletedAt        *int64
	ErrorCode          *string
	MatchedRuleIdsJson []byte
	EventJson          []byte
	Title              string
	Body               string
	CreatedAt          int64
	UpdatedAt          int64
}

func (q *Queries) CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createNotificationDelivery,
		arg.ID,
		arg.EventID,
		arg.SenderID,
		arg.SenderName,
		arg.SenderKind,
		arg.EventType,
		arg.NodeID,
		arg.EgressID,
		arg.IsTest,
		arg.Status,
		arg.AttemptCount,
		arg.NextAttemptAt,
		arg.LastAttemptAt,
		arg.CompletedAt,
		arg.ErrorCode,
		arg.MatchedRuleIdsJson,
		arg.EventJson,
		arg.Title,
		arg.Body,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createNotificationEvent = `-- name: CreateNotificationEvent :execrows
INSERT INTO notification_events (
    id, event_type, source_kind, source_id, node_id, egress_id,
    payload_json, observed_at, recorded_at, processed_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (source_kind, source_id, event_type) DO NOTHING
`

type CreateNotificationEventParams struct {
	ID          string
	EventType   string
	SourceKind  string
	SourceID    string
	NodeID      *string
	EgressID    *string
	PayloadJson []byte
	ObservedAt  int64
	RecordedAt  int64
	ProcessedAt *int64
}

func (q *Queries) CreateNotificationEvent(ctx context.Context, arg CreateNotificationEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createNotificationEvent,
		arg.ID,
		arg.EventType,
		arg.SourceKind,
		arg.SourceID,
		arg.NodeID,
		arg.EgressID,
		arg.PayloadJson,
		arg.ObservedAt,
		arg.RecordedAt,
		arg.ProcessedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createProbeChangeSet = `-- name: CreateProbeChangeSet :execrows
INSERT INTO probe_change_sets (
    id, execution_id, snapshot_id, egress_id, sequence,
    previous_snapshot_id, baseline, change_count, observed_at, recorded_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (execution_id) DO NOTHING
`

type CreateProbeChangeSetParams struct {
	ID                 string
	ExecutionID        string
	SnapshotID         string
	EgressID           string
	Sequence           int64
	PreviousSnapshotID *string
	Baseline           int64
	ChangeCount        int64
	ObservedAt         int64
	RecordedAt         int64
}

func (q *Queries) CreateProbeChangeSet(ctx context.Context, arg CreateProbeChangeSetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProbeChangeSet,
		arg.ID,
		arg.ExecutionID,
		arg.SnapshotID,
		arg.EgressID,
		arg.Sequence,
		arg.PreviousSnapshotID,
		arg.Baseline,
		arg.ChangeCount,
		arg.ObservedAt,
		arg.RecordedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createProbeExecution = `-- name: CreateProbeExecution :execrows
INSERT INTO probe_executions (
    id, run_id, egress_id, ordinal, sequence, status, started_at,
    completed_at, failure_stage, diagnostic, received_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type CreateProbeExecutionParams struct {
	ID           string
	RunID        string
	EgressID     string
	Ordinal      int64
	Sequence     int64
	Status       string
	StartedAt    *int64
	CompletedAt  *int64
	FailureStage *string
	Diagnostic   *string
	ReceivedAt   int64
}

func (q *Queries) CreateProbeExecution(ctx context.Context, arg CreateProbeExecutionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProbeExecution,
		arg.ID,
		arg.RunID,
		arg.EgressID,
		arg.Ordinal,
		arg.Sequence,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.FailureStage,
		arg.Diagnostic,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createProbeFieldChange = `-- name: CreateProbeFieldChange :execrows
INSERT INTO probe_field_changes (
    change_set_id, field_id, group_name, json_path, value_type,
    before_value, after_value
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (change_set_id, field_id) DO NOTHING
`

type CreateProbeFieldChangeParams struct {
	ChangeSetID string
	FieldID     string
	GroupName   string
	JsonPath    string
	ValueType   string
	BeforeValue string
	AfterValue  string
}

func (q *Queries) CreateProbeFieldChange(ctx context.Context, arg CreateProbeFieldChangeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProbeFieldChange,
		arg.ChangeSetID,
		arg.FieldID,
		arg.GroupName,
		arg.JsonPath,
		arg.ValueType,
		arg.BeforeValue,
		arg.AfterValue,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createProbeFormatEvent = `-- name: CreateProbeFormatEvent :execrows
INSERT INTO probe_format_events (
    id, execution_id, snapshot_id, egress_id, sequence, kind,
    previous_signature, current_signature, issue_count, issues_json,
    observed_at, recorded_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (execution_id) DO NOTHING
`

type CreateProbeFormatEventParams struct {
	ID                string
	ExecutionID       string
	SnapshotID        string
	EgressID          string
	Sequence          int64
	Kind              string
	PreviousSignature *string
	CurrentSignature  string
	IssueCount        int64
	IssuesJson        []byte
	ObservedAt        int64
	RecordedAt        int64
}

func (q *Queries) CreateProbeFormatEvent(ctx context.Context, arg CreateProbeFormatEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProbeFormatEvent,
		arg.ID,
		arg.ExecutionID,
		arg.SnapshotID,
		arg.EgressID,
		arg.Sequence,
		arg.Kind,
		arg.PreviousSignature,
		arg.CurrentSignature,
		arg.IssueCount,
		arg.IssuesJson,
		arg.ObservedAt,
		arg.RecordedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createProbeRun = `-- name: CreateProbeRun :execrows
INSERT INTO probe_runs (
    id, node_id, history_generation, configuration_revision, trigger,
    task_id, status, expected_executions,
    started_at, completed_at, received_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type CreateProbeRunParams struct {
	ID                    string
	NodeID                string
	HistoryGeneration     string
	ConfigurationRevision int64
	Trigger               string
	TaskID                *string
	Status                string
	ExpectedExecutions    int64
	StartedAt             int64
	CompletedAt           *int64
	ReceivedAt            int64
}

func (q *Queries) CreateProbeRun(ctx context.Context, arg CreateProbeRunParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProbeRun,
		arg.ID,
		arg.NodeID,
		arg.HistoryGeneration,
		arg.ConfigurationRevision,
		arg.Trigger,
		arg.TaskID,
		arg.Status,
		arg.ExpectedExecutions,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createProbeSnapshot = `-- name: CreateProbeSnapshot :execrows
INSERT INTO probe_snapshots (
    id, execution_id, egress_id, sequence, observed_at, raw_result,
    encoded_size, received_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO NOTHING
`

type CreateProbeSnapshotParams struct {
	ID          string
	ExecutionID string
	EgressID    string
	Sequence    int64
	ObservedAt  int64
	RawResult   []byte
	EncodedSize int64
	ReceivedAt  int64
}

func (q *Queries) CreateProbeSnapshot(ctx context.Context, arg CreateProbeSnapshotParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProbeSnapshot,
		arg.ID,
		arg.ExecutionID,
		arg.EgressID,
		arg.Sequence,
		arg.ObservedAt,
		arg.RawResult,
		arg.EncodedSize,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createProbeSnapshotFormat = `-- name: CreateProbeSnapshotFormat :execrows
INSERT INTO probe_snapshot_formats (
    snapshot_id, status, signature, issue_count, issues_json
) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (snapshot_id) DO NOTHING
`

type CreateProbeSnapshotFormatParams struct {
	SnapshotID string
	Status     string
	Signature  string
	IssueCount int64
	IssuesJson []byte
}

func (q *Queries) CreateProbeSnapshotFormat(ctx context.Context, arg CreateProbeSnapshotFormatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createProbeSnapshotFormat,
		arg.SnapshotID,
		arg.Status,
		arg.Signature,
		arg.IssueCount,
		arg.IssuesJson,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteEgressAddressGaps = `-- name: DeleteEgressAddressGaps :exec
DELETE FROM history_gaps WHERE egress_id = ?
`

func (q *Queries) DeleteEgressAddressGaps(ctx context.Context, egressID string) error {
	_, err := q.db.ExecContext(ctx, deleteEgressAddressGaps, egressID)
	return err
}

const deleteEgressAddressStates = `-- name: DeleteEgressAddressStates :exec
DELETE FROM address_states WHERE egress_id = ?
`

func (q *Queries) DeleteEgressAddressStates(ctx context.Context, egressID string) error {
	_, err := q.db.ExecContext(ctx, deleteEgressAddressStates, egressID)
	return err
}

const deleteEmptyProbeRuns = `-- name: DeleteEmptyProbeRuns :exec
DELETE FROM probe_runs
WHERE NOT EXISTS (
    SELECT 1 FROM probe_executions e WHERE e.run_id = probe_runs.id
)
`

func (q *Queries) DeleteEmptyProbeRuns(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteEmptyProbeRuns)
	return err
}

const deleteNodeAddressEvents = `-- name: DeleteNodeAddressEvents :exec
DELETE FROM address_events WHERE node_id = ?
`

func (q *Queries) DeleteNodeAddressEvents(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeAddressEvents, nodeID)
	return err
}

const deleteNodeAddressGaps = `-- name: DeleteNodeAddressGaps :exec
DELETE FROM history_gaps WHERE node_id = ?
`

func (q *Queries) DeleteNodeAddressGaps(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeAddressGaps, nodeID)
	return err
}

const deleteNodeAddressNotificationHistory = `-- name: DeleteNodeAddressNotificationHistory :exec
DELETE FROM notification_events
WHERE node_id = ? AND egress_id IS NULL
`

func (q *Queries) DeleteNodeAddressNotificationHistory(ctx context.Context, nodeID *string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeAddressNotificationHistory, nodeID)
	return err
}

const deleteNodeAddressStates = `-- name: DeleteNodeAddressStates :exec
DELETE FROM address_states WHERE node_id = ?
`

func (q *Queries) DeleteNodeAddressStates(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeAddressStates, nodeID)
	return err
}

const deleteNodeNotificationHistory = `-- name: DeleteNodeNotificationHistory :exec
DELETE FROM notification_events WHERE node_id = ?
`

func (q *Queries) DeleteNodeNotificationHistory(ctx context.Context, nodeID *string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeNotificationHistory, nodeID)
	return err
}

const deleteNodeProbeComparisonProgress = `-- name: DeleteNodeProbeComparisonProgress :exec
DELETE FROM probe_comparison_progress WHERE node_id = ?
`

func (q *Queries) DeleteNodeProbeComparisonProgress(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeProbeComparisonProgress, nodeID)
	return err
}

const deleteNodeProbeGaps = `-- name: DeleteNodeProbeGaps :exec
DELETE FROM probe_gaps WHERE node_id = ?
`

func (q *Queries) DeleteNodeProbeGaps(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeProbeGaps, nodeID)
	return err
}

const deleteNodeProbeHistory = `-- name: DeleteNodeProbeHistory :exec
DELETE FROM probe_runs WHERE node_id = ?
`

func (q *Queries) DeleteNodeProbeHistory(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeProbeHistory, nodeID)
	return err
}

const deleteNodeProbeOutcomeStates = `-- name: DeleteNodeProbeOutcomeStates :exec
DELETE FROM probe_outcome_states WHERE node_id = ?
`

func (q *Queries) DeleteNodeProbeOutcomeStates(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeProbeOutcomeStates, nodeID)
	return err
}

const deleteProbeOutcomeState = `-- name: DeleteProbeOutcomeState :exec
DELETE FROM probe_outcome_states WHERE egress_id = ?
`

func (q *Queries) DeleteProbeOutcomeState(ctx context.Context, egressID string) error {
	_, err := q.db.ExecContext(ctx, deleteProbeOutcomeState, egressID)
	return err
}

const deleteRetentionAddressEvent = `-- name: DeleteRetentionAddressEvent :execrows
DELETE FROM address_events WHERE id = ?
`

func (q *Queries) DeleteRetentionAddressEvent(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRetentionAddressEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRetentionAddressGap = `-- name: DeleteRetentionAddressGap :execrows
DELETE FROM history_gaps WHERE id = ?
`

func (q *Queries) DeleteRetentionAddressGap(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRetentionAddressGap, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRetentionExecution = `-- name: DeleteRetentionExecution :execrows
DELETE FROM probe_executions
WHERE probe_executions.id = ? AND probe_executions.status NOT IN ('pending', 'running')
  AND EXISTS(
      SELECT 1 FROM probe_runs run
      WHERE run.id = probe_executions.run_id AND run.status != 'running'
  )
  AND NOT EXISTS(
      SELECT 1 FROM probe_snapshots s
      JOIN probe_snapshot_stars star ON star.snapshot_id = s.id
      WHERE s.execution_id = probe_executions.id
  )
  AND NOT EXISTS(
      SELECT 1 FROM probe_snapshots s
      JOIN current_probe_snapshots current ON current.snapshot_id = s.id
      WHERE s.execution_id = probe_executions.id
  )
  AND NOT EXISTS(
      SELECT 1 FROM probe_snapshots s
      JOIN probe_format_states state ON state.snapshot_id = s.id
      WHERE s.execution_id = probe_executions.id
  )
  AND NOT EXISTS(
      SELECT 1 FROM probe_snapshots s
      JOIN probe_comparison_progress progress ON progress.last_success_snapshot_id = s.id
      WHERE s.execution_id = probe_executions.id
  )
  AND NOT EXISTS(
      SELECT 1 FROM probe_outcome_states outcome
      WHERE outcome.execution_id = probe_executions.id
  )
`

func (q *Queries) DeleteRetentionExecution(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRetentionExecution, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRetentionNotificationEvent = `-- name: DeleteRetentionNotificationEvent :execrows
DELETE FROM notification_events
WHERE notification_events.id = ? AND processed_at IS NOT NULL
  AND NOT EXISTS(
      SELECT 1 FROM notification_deliveries delivery
      WHERE delivery.event_id = notification_events.id
        AND delivery.status IN ('pending', 'running', 'retrying')
  )
`

func (q *Queries) DeleteRetentionNotificationEvent(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRetentionNotificationEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRetentionProbeGap = `-- name: DeleteRetentionProbeGap :execrows
DELETE FROM probe_gaps WHERE id = ?
`

func (q *Queries) DeleteRetentionProbeGap(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRetentionProbeGap, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failNotificationDelivery = `-- name: FailNotificationDelivery :execrows
UPDATE notification_deliveries
SET status = 'failed', next_attempt_at = NULL, completed_at = ?,
    error_code = ?, updated_at = ?
WHERE id = ? AND status = 'running'
`

type FailNotificationDeliveryParams struct {
	CompletedAt *int64
	ErrorCode   *string
	UpdatedAt   int64
	ID          string
}

func (q *Queries) FailNotificationDelivery(ctx context.Context, arg FailNotificationDeliveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failNotificationDelivery,
		arg.CompletedAt,
		arg.ErrorCode,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAddressEvent = `-- name: GetAddressEvent :one
SELECT id, public_address_id, source_path_id, node_id, history_generation, sequence, kind, family,
       public_address, local_interface, local_address,
       proxy_path, likely_nat, temporary, failure_reason, observed_at,
       received_at
FROM address_events
WHERE id = ?
`

func (q *Queries) GetAddressEvent(ctx context.Context, id string) (AddressEvent, error) {
	row := q.db.QueryRowContext(ctx, getAddressEvent, id)
	var i AddressEvent
	err := row.Scan(
		&i.ID,
		&i.PublicAddressID,
		&i.SourcePathID,
		&i.NodeID,
		&i.HistoryGeneration,
		&i.Sequence,
		&i.Kind,
		&i.Family,
		&i.PublicAddress,
		&i.LocalInterface,
		&i.LocalAddress,
		&i.ProxyPath,
		&i.LikelyNat,
		&i.Temporary,
		&i.FailureReason,
		&i.ObservedAt,
		&i.ReceivedAt,
	)
	return i, err
}

const getAddressEventBySequence = `-- name: GetAddressEventBySequence :one
SELECT id, public_address_id, source_path_id, node_id, history_generation, sequence, kind, family,
       public_address, local_interface, local_address,
       proxy_path, likely_nat, temporary, failure_reason, observed_at,
       received_at
FROM address_events
WHERE source_path_id = ? AND history_generation = ? AND sequence = ?
`

type GetAddressEventBySequenceParams struct {
	SourcePathID      string
	HistoryGeneration string
	Sequence          int64
}

func (q *Queries) GetAddressEventBySequence(ctx context.Context, arg GetAddressEventBySequenceParams) (AddressEvent, error) {
	row := q.db.QueryRowContext(ctx, getAddressEventBySequence, arg.SourcePathID, arg.HistoryGeneration, arg.Sequence)
	var i AddressEvent
	err := row.Scan(
		&i.ID,
		&i.PublicAddressID,
		&i.SourcePathID,
		&i.NodeID,
		&i.HistoryGeneration,
		&i.Sequence,
		&i.Kind,
		&i.Family,
		&i.PublicAddress,
		&i.LocalInterface,
		&i.LocalAddress,
		&i.ProxyPath,
		&i.LikelyNat,
		&i.Temporary,
		&i.FailureReason,
		&i.ObservedAt,
		&i.ReceivedAt,
	)
	return i, err
}

const getHistoryLogicalUsage = `-- name: GetHistoryLogicalUsage :one
SELECT
    CAST(COALESCE(SUM(logical_bytes), 0) AS INTEGER) AS logical_bytes,
    CAST(COALESCE(SUM(record_count), 0) AS INTEGER) AS record_count
FROM (
    SELECT SUM(encoded_size + 160) AS logical_bytes, COUNT(*) AS record_count FROM probe_snapshots
    UNION ALL SELECT SUM(
        256 + length(id) + length(run_id) + length(egress_id) +
        COALESCE(length(failure_stage), 0) + COALESCE(length(CAST(diagnostic AS BLOB)), 0)
    ), COUNT(*) FROM probe_executions
    UNION ALL SELECT SUM(
        256 + length(id) + length(node_id) + length(history_generation) +
        length(trigger) + COALESCE(length(task_id), 0)
    ), COUNT(*) FROM probe_runs
    UNION ALL SELECT SUM(
        256 + length(id) + length(public_address_id) + length(source_path_id) + length(node_id) +
        COALESCE(length(public_address), 0) +
        COALESCE(length(local_interface), 0) + COALESCE(length(local_address), 0) +
        COALESCE(length(proxy_path), 0) + COALESCE(length(failure_reason), 0)
    ), COUNT(*) FROM address_events
    UNION ALL SELECT COUNT(*) * 224, COUNT(*) FROM history_gaps
    UNION ALL SELECT COUNT(*) * 224, COUNT(*) FROM probe_gaps
    UNION ALL SELECT SUM(192 + length(issues_json)), COUNT(*) FROM probe_snapshot_formats
    UNION ALL SELECT SUM(256 + length(issues_json)), COUNT(*) FROM probe_format_states
    UNION ALL SELECT SUM(256 + length(issues_json)), COUNT(*) FROM probe_format_events
    UNION ALL SELECT COUNT(*) * 256, COUNT(*) FROM probe_change_sets
    UNION ALL SELECT SUM(
        160 + length(field_id) + length(group_name) + length(json_path) +
        length(CAST(before_value AS BLOB)) + length(CAST(after_value AS BLOB))
    ), COUNT(*) FROM probe_field_changes
    UNION ALL SELECT COUNT(*) * 96, COUNT(*) FROM probe_snapshot_stars
    UNION ALL SELECT COUNT(*) * 192, COUNT(*) FROM probe_comparison_progress
    UNION ALL SELECT COUNT(*) * 160, COUNT(*) FROM current_probe_snapshots
    UNION ALL SELECT COUNT(*) * 224, COUNT(*) FROM probe_outcome_states
    UNION ALL SELECT SUM(
        256 + length(id) + length(event_type) + length(source_kind) + length(source_id) +
        COALESCE(length(node_id), 0) + COALESCE(length(egress_id), 0) + length(payload_json)
    ), COUNT(*) FROM notification_events
    UNION ALL SELECT SUM(
        512 + length(id) + length(event_id) + length(sender_id) + length(sender_name) +
        length(sender_kind) + length(event_type) + length(matched_rule_ids_json) +
        length(event_json) + length(CAST(title AS BLOB)) + length(CAST(body AS BLOB)) +
        COALESCE(length(error_code), 0)
    ), COUNT(*) FROM notification_deliveries
    UNION ALL SELECT SUM(
        256 + COALESCE(length(public_address), 0) + COALESCE(length(local_interface), 0) +
        COALESCE(length(local_address), 0) + COALESCE(length(proxy_path), 0) +
        COALESCE(length(failure_reason), 0)
    ), COUNT(*) FROM address_states
)
`

type GetHistoryLogicalUsageRow struct {
	LogicalBytes int64
	RecordCount  int64
}

func (q *Queries) GetHistoryLogicalUsage(ctx context.Context) (GetHistoryLogicalUsageRow, error) {
	row := q.db.QueryRowContext(ctx, getHistoryLogicalUsage)
	var i GetHistoryLogicalUsageRow
	err := row.Scan(&i.LogicalBytes, &i.RecordCount)
	return i, err
}

const getHistoryMetadata = `-- name: GetHistoryMetadata :one
SELECT id, generation, created_at
FROM history_metadata
WHERE id = 1
`

func (q *Queries) GetHistoryMetadata(ctx context.Context) (HistoryMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getHistoryMetadata)
	var i HistoryMetadatum
	err := row.Scan(&i.ID, &i.Generation, &i.CreatedAt)
	return i, err
}

const getNotificationDelivery = `-- name: GetNotificationDelivery :one
SELECT id, event_id, sender_id, sender_name, sender_kind, event_type,
       node_id, egress_id, is_test, status, attempt_count, next_attempt_at,
       last_attempt_at, completed_at, error_code, matched_rule_ids_json,
       event_json, title, body, created_at, updated_at
FROM notification_deliveries
WHERE id = ?
`

func (q *Queries) GetNotificationDelivery(ctx context.Context, id string) (NotificationDelivery, error) {
	row := q.db.QueryRowContext(ctx, getNotificationDelivery, id)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.SenderID,
		&i.SenderName,
		&i.SenderKind,
		&i.EventType,
		&i.NodeID,
		&i.EgressID,
		&i.IsTest,
		&i.Status,
		&i.AttemptCount,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.CompletedAt,
		&i.ErrorCode,
		&i.MatchedRuleIdsJson,
		&i.EventJson,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationEvent = `-- name: GetNotificationEvent :one
SELECT id, event_type, source_kind, source_id, node_id, egress_id,
       payload_json, observed_at, recorded_at, processed_at
FROM notification_events
WHERE id = ?
`

func (q *Queries) GetNotificationEvent(ctx context.Context, id string) (NotificationEvent, error) {
	row := q.db.QueryRowContext(ctx, getNotificationEvent, id)
	var i NotificationEvent
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.SourceKind,
		&i.SourceID,
		&i.NodeID,
		&i.EgressID,
		&i.PayloadJson,
		&i.ObservedAt,
		&i.RecordedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getPreviousProbeSnapshotID = `-- name: GetPreviousProbeSnapshotID :one
SELECT id
FROM probe_snapshots
WHERE egress_id = ? AND sequence < ?
ORDER BY sequence DESC
LIMIT 1
`

type GetPreviousProbeSnapshotIDParams struct {
	EgressID string
	Sequence int64
}

func (q *Queries) GetPreviousProbeSnapshotID(ctx context.Context, arg GetPreviousProbeSnapshotIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPreviousProbeSnapshotID, arg.EgressID, arg.Sequence)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getProbeChangeSetBySnapshot = `-- name: GetProbeChangeSetBySnapshot :one
SELECT id, execution_id, snapshot_id, egress_id, sequence,
       previous_snapshot_id, baseline, change_count, observed_at, recorded_at
FROM probe_change_sets
WHERE snapshot_id = ?
`

func (q *Queries) GetProbeChangeSetBySnapshot(ctx context.Context, snapshotID string) (ProbeChangeSet, error) {
	row := q.db.QueryRowContext(ctx, getProbeChangeSetBySnapshot, snapshotID)
	var i ProbeChangeSet
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.SnapshotID,
		&i.EgressID,
		&i.Sequence,
		&i.PreviousSnapshotID,
		&i.Baseline,
		&i.ChangeCount,
		&i.ObservedAt,
		&i.RecordedAt,
	)
	return i, err
}

const getProbeComparisonProgress = `-- name: GetProbeComparisonProgress :one
SELECT egress_id, node_id, history_generation, next_sequence,
       last_success_snapshot_id, updated_at
FROM probe_comparison_progress
WHERE egress_id = ?
`

func (q *Queries) GetProbeComparisonProgress(ctx context.Context, egressID string) (ProbeComparisonProgress, error) {
	row := q.db.QueryRowContext(ctx, getProbeComparisonProgress, egressID)
	var i ProbeComparisonProgress
	err := row.Scan(
		&i.EgressID,
		&i.NodeID,
		&i.HistoryGeneration,
		&i.NextSequence,
		&i.LastSuccessSnapshotID,
		&i.UpdatedAt,
	)
	return i, err
}

const getProbeExecution = `-- name: GetProbeExecution :one
SELECT id, run_id, egress_id, ordinal, sequence, status, started_at,
       completed_at, failure_stage, diagnostic, received_at
FROM probe_executions
WHERE id = ?
`

func (q *Queries) GetProbeExecution(ctx context.Context, id string) (ProbeExecution, error) {
	row := q.db.QueryRowContext(ctx, getProbeExecution, id)
	var i ProbeExecution
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.EgressID,
		&i.Ordinal,
		&i.Sequence,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureStage,
		&i.Diagnostic,
		&i.ReceivedAt,
	)
	return i, err
}

const getProbeExecutionByEgressSequence = `-- name: GetProbeExecutionByEgressSequence :one
SELECT id, run_id, egress_id, ordinal, sequence, status, started_at,
       completed_at, failure_stage, diagnostic, received_at
FROM probe_executions
WHERE egress_id = ? AND sequence = ?
`

type GetProbeExecutionByEgressSequenceParams struct {
	EgressID string
	Sequence int64
}

func (q *Queries) GetProbeExecutionByEgressSequence(ctx context.Context, arg GetProbeExecutionByEgressSequenceParams) (ProbeExecution, error) {
	row := q.db.QueryRowContext(ctx, getProbeExecutionByEgressSequence, arg.EgressID, arg.Sequence)
	var i ProbeExecution
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.EgressID,
		&i.Ordinal,
		&i.Sequence,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.FailureStage,
		&i.Diagnostic,
		&i.ReceivedAt,
	)
	return i, err
}

const getProbeFormatState = `-- name: GetProbeFormatState :one
SELECT egress_id, snapshot_id, sequence, status, signature, issue_count,
       issues_json, first_observed_at, last_observed_at, updated_at
FROM probe_format_states
WHERE egress_id = ?
`

func (q *Queries) GetProbeFormatState(ctx context.Context, egressID string) (ProbeFormatState, error) {
	row := q.db.QueryRowContext(ctx, getProbeFormatState, egressID)
	var i ProbeFormatState
	err := row.Scan(
		&i.EgressID,
		&i.SnapshotID,
		&i.Sequence,
		&i.Status,
		&i.Signature,
		&i.IssueCount,
		&i.IssuesJson,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProbeGapCoveringSequence = `-- name: GetProbeGapCoveringSequence :one
SELECT id, egress_id, node_id, history_generation, dropped_count,
       first_sequence, last_sequence, first_observed_at, last_observed_at,
       received_at
FROM probe_gaps
WHERE egress_id = ? AND history_generation = ?
  AND first_sequence <= ? AND last_sequence >= ?
ORDER BY last_sequence DESC, id
LIMIT 1
`

type GetProbeGapCoveringSequenceParams struct {
	EgressID          string
	HistoryGeneration string
	FirstSequence     int64
	LastSequence      int64
}

func (q *Queries) GetProbeGapCoveringSequence(ctx context.Context, arg GetProbeGapCoveringSequenceParams) (ProbeGap, error) {
	row := q.db.QueryRowContext(ctx, getProbeGapCoveringSequence,
		arg.EgressID,
		arg.HistoryGeneration,
		arg.FirstSequence,
		arg.LastSequence,
	)
	var i ProbeGap
	err := row.Scan(
		&i.ID,
		&i.EgressID,
		&i.NodeID,
		&i.HistoryGeneration,
		&i.DroppedCount,
		&i.FirstSequence,
		&i.LastSequence,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.ReceivedAt,
	)
	return i, err
}

const getProbeOutcomeState = `-- name: GetProbeOutcomeState :one
SELECT egress_id, node_id, history_generation, execution_id, sequence,
       status, first_observed_at, last_observed_at, updated_at
FROM probe_outcome_states
WHERE egress_id = ?
`

func (q *Queries) GetProbeOutcomeState(ctx context.Context, egressID string) (ProbeOutcomeState, error) {
	row := q.db.QueryRowContext(ctx, getProbeOutcomeState, egressID)
	var i ProbeOutcomeState
	err := row.Scan(
		&i.EgressID,
		&i.NodeID,
		&i.HistoryGeneration,
		&i.ExecutionID,
		&i.Sequence,
		&i.Status,
		&i.FirstObservedAt,
		&i.LastObservedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProbeRun = `-- name: GetProbeRun :one
SELECT id, node_id, history_generation, configuration_revision, trigger,
       task_id, status, expected_executions,
       started_at, completed_at, received_at
FROM probe_runs
WHERE id = ?
`

func (q *Queries) GetProbeRun(ctx context.Context, id string) (ProbeRun, error) {
	row := q.db.QueryRowContext(ctx, getProbeRun, id)
	var i ProbeRun
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.HistoryGeneration,
		&i.ConfigurationRevision,
		&i.Trigger,
		&i.TaskID,
		&i.Status,
		&i.ExpectedExecutions,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ReceivedAt,
	)
	return i, err
}

const getProbeSnapshot = `-- name: GetProbeSnapshot :one
SELECT id, execution_id, egress_id, sequence, observed_at, raw_result,
       encoded_size, received_at
FROM probe_snapshots
WHERE id = ?
`

func (q *Queries) GetProbeSnapshot(ctx context.Context, id string) (ProbeSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getProbeSnapshot, id)
	var i ProbeSnapshot
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.EgressID,
		&i.Sequence,
		&i.ObservedAt,
		&i.RawResult,
		&i.EncodedSize,
		&i.ReceivedAt,
	)
	return i, err
}

const getProbeSnapshotByExecution = `-- name: GetProbeSnapshotByExecution :one
SELECT id, execution_id, egress_id, sequence, observed_at, raw_result,
       encoded_size, received_at
FROM probe_snapshots
WHERE execution_id = ?
`

func (q *Queries) GetProbeSnapshotByExecution(ctx context.Context, executionID string) (ProbeSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getProbeSnapshotByExecution, executionID)
	var i ProbeSnapshot
	err := row.Scan(
		&i.ID,
		&i.ExecutionID,
		&i.EgressID,
		&i.Sequence,
		&i.ObservedAt,
		&i.RawResult,
		&i.EncodedSize,
		&i.ReceivedAt,
	)
	return i, err
}

const getProbeSnapshotFormat = `-- name: GetProbeSnapshotFormat :one
SELECT snapshot_id, status, signature, issue_count, issues_json
FROM probe_snapshot_formats
WHERE snapshot_id = ?
`

func (q *Queries) GetProbeSnapshotFormat(ctx context.Context, snapshotID string) (ProbeSnapshotFormat, error) {
	row := q.db.QueryRowContext(ctx, getProbeSnapshotFormat, snapshotID)
	var i ProbeSnapshotFormat
	err := row.Scan(
		&i.SnapshotID,
		&i.Status,
		&i.Signature,
		&i.IssueCount,
		&i.IssuesJson,
	)
	return i, err
}

const getProtectedHistoryLogicalBytes = `-- name: GetProtectedHistoryLogicalBytes :one
WITH protected_snapshots AS (
    SELECT s.id, s.execution_id, s.encoded_size
    FROM probe_snapshots s
    JOIN probe_executions e ON e.id = s.execution_id
    JOIN probe_runs r ON r.id = e.run_id
    WHERE r.status = 'running'
       OR e.status IN ('pending', 'running')
       OR EXISTS(SELECT 1 FROM probe_snapshot_stars star WHERE star.snapshot_id = s.id)
       OR EXISTS(SELECT 1 FROM current_probe_snapshots current WHERE current.snapshot_id = s.id)
       OR EXISTS(SELECT 1 FROM probe_format_states state WHERE state.snapshot_id = s.id)
       OR EXISTS(
           SELECT 1 FROM probe_comparison_progress progress
           WHERE progress.last_success_snapshot_id = s.id
       )
), protected_executions AS (
    SELECT e.id, e.run_id, e.egress_id, e.failure_stage, e.diagnostic
    FROM probe_executions e
    JOIN probe_runs r ON r.id = e.run_id
    WHERE r.status = 'running'
       OR e.status IN ('pending', 'running')
       OR EXISTS(SELECT 1 FROM protected_snapshots snapshot WHERE snapshot.execution_id = e.id)
       OR EXISTS(SELECT 1 FROM probe_outcome_states outcome WHERE outcome.execution_id = e.id)
), protected_runs AS (
    SELECT r.id, r.node_id, r.history_generation, r.trigger, r.task_id
    FROM probe_runs r
    WHERE r.status = 'running'
       OR EXISTS(SELECT 1 FROM protected_executions execution WHERE execution.run_id = r.id)
)
SELECT CAST(COALESCE(SUM(logical_bytes), 0) AS INTEGER) AS logical_bytes
FROM (
    SELECT SUM(encoded_size + 160) AS logical_bytes FROM protected_snapshots
    UNION ALL
    SELECT SUM(
        256 + length(id) + length(run_id) + length(egress_id) +
        COALESCE(length(failure_stage), 0) + COALESCE(length(CAST(diagnostic AS BLOB)), 0)
    ) FROM protected_executions
    UNION ALL
    SELECT SUM(
        256 + length(id) + length(node_id) + length(history_generation) +
        length(trigger) + COALESCE(length(task_id), 0)
    ) FROM protected_runs
    UNION ALL
    SELECT SUM(192 + length(format.issues_json))
    FROM probe_snapshot_formats format
    JOIN protected_snapshots snapshot ON snapshot.id = format.snapshot_id
    UNION ALL
    SELECT SUM(256 + length(event.issues_json))
    FROM probe_format_events event
    JOIN protected_snapshots snapshot ON snapshot.id = event.snapshot_id
    UNION ALL
    SELECT COUNT(*) * 256
    FROM probe_change_sets change_set
    JOIN protected_snapshots snapshot ON snapshot.id = change_set.snapshot_id
    UNION ALL
    SELECT SUM(
        160 + length(change.field_id) + length(change.group_name) + length(change.json_path) +
        length(CAST(change.before_value AS BLOB)) + length(CAST(change.after_value AS BLOB))
    )
    FROM probe_field_changes change
    JOIN probe_change_sets change_set ON change_set.id = change.change_set_id
    JOIN protected_snapshots snapshot ON snapshot.id = change_set.snapshot_id
    UNION ALL
    SELECT COUNT(*) * 96 FROM probe_snapshot_stars
    UNION ALL
    SELECT COUNT(*) * 160 FROM current_probe_snapshots
    UNION ALL
    SELECT SUM(256 + length(issues_json)) FROM probe_format_states
    UNION ALL
    SELECT SUM(
        256 + COALESCE(length(public_address), 0) + COALESCE(length(local_interface), 0) +
        COALESCE(length(local_address), 0) + COALESCE(length(proxy_path), 0) +
        COALESCE(length(failure_reason), 0)
    ) FROM address_states
    UNION ALL
    SELECT COUNT(*) * 192 FROM probe_comparison_progress
    UNION ALL
    SELECT COUNT(*) * 224 FROM probe_outcome_states
    UNION ALL
    SELECT SUM(
        256 + length(event.id) + length(event.event_type) + length(event.source_kind) +
        length(event.source_id) + COALESCE(length(event.node_id), 0) +
        COALESCE(length(event.egress_id), 0) + length(event.payload_json)
    )
    FROM notification_events event
    WHERE event.processed_at IS NULL OR EXISTS(
        SELECT 1 FROM notification_deliveries delivery
        WHERE delivery.event_id = event.id
          AND delivery.status IN ('pending', 'running', 'retrying')
    )
    UNION ALL
    SELECT SUM(
        512 + length(id) + length(event_id) + length(sender_id) + length(sender_name) +
        length(sender_kind) + length(event_type) + length(matched_rule_ids_json) +
        length(event_json) + length(CAST(title AS BLOB)) + length(CAST(body AS BLOB)) +
        COALESCE(length(error_code), 0)
    )
    FROM notification_deliveries
    WHERE status IN ('pending', 'running', 'retrying')
)
`

func (q *Queries) GetProtectedHistoryLogicalBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProtectedHistoryLogicalBytes)
	var logical_bytes int64
	err := row.Scan(&logical_bytes)
	return logical_bytes, err
}

const isProbeSnapshotStarred = `-- name: IsProbeSnapshotStarred :one
SELECT EXISTS(
    SELECT 1 FROM probe_snapshot_stars WHERE snapshot_id = ?
) AS starred
`

func (q *Queries) IsProbeSnapshotStarred(ctx context.Context, snapshotID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, isProbeSnapshotStarred, snapshotID)
	var starred bool
	err := row.Scan(&starred)
	return starred, err
}

const listCurrentProbeSnapshots = `-- name: ListCurrentProbeSnapshots :many
SELECT egress_id, snapshot_id, observed_at
FROM current_probe_snapshots
ORDER BY egress_id
`

type ListCurrentProbeSnapshotsRow struct {
	EgressID   string
	SnapshotID string
	ObservedAt int64
}

func (q *Queries) ListCurrentProbeSnapshots(ctx context.Context) ([]ListCurrentProbeSnapshotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentProbeSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentProbeSnapshotsRow{}
	for rows.Next() {
		var i ListCurrentProbeSnapshotsRow
		if err := rows.Scan(&i.EgressID, &i.SnapshotID, &i.ObservedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalAddressEvents = `-- name: ListGlobalAddressEvents :many
SELECT id, public_address_id, source_path_id, node_id, history_generation, sequence, kind, family,
       public_address, local_interface, local_address,
       proxy_path, likely_nat, temporary, failure_reason, observed_at,
       received_at
FROM address_events
WHERE (?1 = '' OR node_id = ?1)
  AND (?2 = '' OR public_address_id = ?2)
  AND (?3 IS NULL OR observed_at >= ?3)
  AND (?4 IS NULL OR observed_at <= ?4)
  AND (?5 = '' OR kind = ?5)
  AND (?6 = '' OR family = ?6)
ORDER BY observed_at DESC, id DESC
LIMIT ?8 OFFSET ?7
`

type ListGlobalAddressEventsParams struct {
	NodeID         interface{}
	EgressID       interface{}
	FromObservedAt interface{}
	ToObservedAt   interface{}
	EventKind      interface{}
	Family         interface{}
	PageOffset     int64
	PageSize       int64
}

func (q *Queries) ListGlobalAddressEvents(ctx context.Context, arg ListGlobalAddressEventsParams) ([]AddressEvent, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalAddressEvents,
		arg.NodeID,
		arg.EgressID,
		arg.FromObservedAt,
		arg.ToObservedAt,
		arg.EventKind,
		arg.Family,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AddressEvent{}
	for rows.Next() {
		var i AddressEvent
		if err := rows.Scan(
			&i.ID,
			&i.PublicAddressID,
			&i.SourcePathID,
			&i.NodeID,
			&i.HistoryGeneration,
			&i.Sequence,
			&i.Kind,
			&i.Family,
			&i.PublicAddress,
			&i.LocalInterface,
			&i.LocalAddress,
			&i.ProxyPath,
			&i.LikelyNat,
			&i.Temporary,
			&i.FailureReason,
			&i.ObservedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalAddressGaps = `-- name: ListGlobalAddressGaps :many
SELECT id, egress_id, node_id, history_generation, kind, dropped_count,
       first_sequence, last_sequence, first_observed_at, last_observed_at,
       received_at
FROM history_gaps
WHERE (?1 = '' OR node_id = ?1)
  AND (?2 = '' OR egress_id = ?2)
  AND (?3 IS NULL OR last_observed_at >= ?3)
  AND (?4 IS NULL OR last_observed_at <= ?4)
ORDER BY last_observed_at DESC, id DESC
LIMIT ?6 OFFSET ?5
`

type ListGlobalAddressGapsParams struct {
	NodeID         interface{}
	EgressID       interface{}
	FromObservedAt interface{}
	ToObservedAt   interface{}
	PageOffset     int64
	PageSize       int64
}

func (q *Queries) ListGlobalAddressGaps(ctx context.Context, arg ListGlobalAddressGapsParams) ([]HistoryGap, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalAddressGaps,
		arg.NodeID,
		arg.EgressID,
		arg.FromObservedAt,
		arg.ToObservedAt,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HistoryGap{}
	for rows.Next() {
		var i HistoryGap
		if err := rows.Scan(
			&i.ID,
			&i.EgressID,
			&i.NodeID,
			&i.HistoryGeneration,
			&i.Kind,
			&i.DroppedCount,
			&i.FirstSequence,
			&i.LastSequence,
			&i.FirstObservedAt,
			&i.LastObservedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalFormatEvents = `-- name: ListGlobalFormatEvents :many
SELECT f.id, f.execution_id, f.snapshot_id, f.egress_id, f.sequence, f.kind,
       f.previous_signature, f.current_signature, f.issue_count, f.issues_json,
       f.observed_at, f.recorded_at, r.node_id
FROM probe_format_events f
JOIN probe_executions e ON e.id = f.execution_id
JOIN probe_runs r ON r.id = e.run_id
WHERE (?1 = '' OR r.node_id = ?1)
  AND (?2 = '' OR f.egress_id = ?2)
  AND (?3 IS NULL OR f.observed_at >= ?3)
  AND (?4 IS NULL OR f.observed_at <= ?4)
ORDER BY f.observed_at DESC, f.id DESC
LIMIT ?6 OFFSET ?5
`

type ListGlobalFormatEventsParams struct {
	NodeID         interface{}
	EgressID       interface{}
	FromObservedAt interface{}
	ToObservedAt   interface{}
	PageOffset     int64
	PageSize       int64
}

type ListGlobalFormatEventsRow struct {
	ID                string
	ExecutionID       string
	SnapshotID        string
	EgressID          string
	Sequence          int64
	Kind              string
	PreviousSignature *string
	CurrentSignature  string
	IssueCount        int64
	IssuesJson        []byte
	ObservedAt        int64
	RecordedAt        int64
	NodeID            string
}

func (q *Queries) ListGlobalFormatEvents(ctx context.Context, arg ListGlobalFormatEventsParams) ([]ListGlobalFormatEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalFormatEvents,
		arg.NodeID,
		arg.EgressID,
		arg.FromObservedAt,
		arg.ToObservedAt,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGlobalFormatEventsRow{}
	for rows.Next() {
		var i ListGlobalFormatEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.SnapshotID,
			&i.EgressID,
			&i.Sequence,
			&i.Kind,
			&i.PreviousSignature,
			&i.CurrentSignature,
			&i.IssueCount,
			&i.IssuesJson,
			&i.ObservedAt,
			&i.RecordedAt,
			&i.NodeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalProbeGaps = `-- name: ListGlobalProbeGaps :many
SELECT id, egress_id, node_id, history_generation, dropped_count,
       first_sequence, last_sequence, first_observed_at, last_observed_at,
       received_at
FROM probe_gaps
WHERE (?1 = '' OR node_id = ?1)
  AND (?2 = '' OR egress_id = ?2)
  AND (?3 IS NULL OR last_observed_at >= ?3)
  AND (?4 IS NULL OR last_observed_at <= ?4)
ORDER BY last_observed_at DESC, id DESC
LIMIT ?6 OFFSET ?5
`

type ListGlobalProbeGapsParams struct {
	NodeID         interface{}
	EgressID       interface{}
	FromObservedAt interface{}
	ToObservedAt   interface{}
	PageOffset     int64
	PageSize       int64
}

func (q *Queries) ListGlobalProbeGaps(ctx context.Context, arg ListGlobalProbeGapsParams) ([]ProbeGap, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalProbeGaps,
		arg.NodeID,
		arg.EgressID,
		arg.FromObservedAt,
		arg.ToObservedAt,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProbeGap{}
	for rows.Next() {
		var i ProbeGap
		if err := rows.Scan(
			&i.ID,
			&i.EgressID,
			&i.NodeID,
			&i.HistoryGeneration,
			&i.DroppedCount,
			&i.FirstSequence,
			&i.LastSequence,
			&i.FirstObservedAt,
			&i.LastObservedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeAddressEvents = `-- name: ListNodeAddressEvents :many
SELECT id, public_address_id, source_path_id, node_id, history_generation, sequence, kind, family,
       public_address, local_interface, local_address,
       proxy_path, likely_nat, temporary, failure_reason, observed_at,
       received_at
FROM address_events
WHERE node_id = ?
ORDER BY observed_at DESC, sequence DESC, id
LIMIT ?
`

type ListNodeAddressEventsParams struct {
	NodeID string
	Limit  int64
}

func (q *Queries) ListNodeAddressEvents(ctx context.Context, arg ListNodeAddressEventsParams) ([]AddressEvent, error) {
	rows, err := q.db.QueryContext(ctx, listNodeAddressEvents, arg.NodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AddressEvent{}
	for rows.Next() {
		var i AddressEvent
		if err := rows.Scan(
			&i.ID,
			&i.PublicAddressID,
			&i.SourcePathID,
			&i.NodeID,
			&i.HistoryGeneration,
			&i.Sequence,
			&i.Kind,
			&i.Family,
			&i.PublicAddress,
			&i.LocalInterface,
			&i.LocalAddress,
			&i.ProxyPath,
			&i.LikelyNat,
			&i.Temporary,
			&i.FailureReason,
			&i.ObservedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeAddressGaps = `-- name: ListNodeAddressGaps :many
SELECT id, egress_id, node_id, history_generation, kind, dropped_count,
       first_sequence, last_sequence, first_observed_at, last_observed_at,
       received_at
FROM history_gaps
WHERE node_id = ?
ORDER BY last_observed_at DESC, id
LIMIT ?
`

type ListNodeAddressGapsParams struct {
	NodeID string
	Limit  int64
}

func (q *Queries) ListNodeAddressGaps(ctx context.Context, arg ListNodeAddressGapsParams) ([]HistoryGap, error) {
	rows, err := q.db.QueryContext(ctx, listNodeAddressGaps, arg.NodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HistoryGap{}
	for rows.Next() {
		var i HistoryGap
		if err := rows.Scan(
			&i.ID,
			&i.EgressID,
			&i.NodeID,
			&i.HistoryGeneration,
			&i.Kind,
			&i.DroppedCount,
			&i.FirstSequence,
			&i.LastSequence,
			&i.FirstObservedAt,
			&i.LastObservedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeAddressStates = `-- name: ListNodeAddressStates :many
SELECT egress_id, node_id, history_generation, family, status, sequence,
       public_address, local_interface, local_address, proxy_path, likely_nat,
       temporary, failure_reason, last_checked_at, last_succeeded_at,
       last_changed_at, received_at
FROM address_states
WHERE node_id = ?
ORDER BY egress_id
`

func (q *Queries) ListNodeAddressStates(ctx context.Context, nodeID string) ([]AddressState, error) {
	rows, err := q.db.QueryContext(ctx, listNodeAddressStates, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AddressState{}
	for rows.Next() {
		var i AddressState
		if err := rows.Scan(
			&i.EgressID,
			&i.NodeID,
			&i.HistoryGeneration,
			&i.Family,
			&i.Status,
			&i.Sequence,
			&i.PublicAddress,
			&i.LocalInterface,
			&i.LocalAddress,
			&i.ProxyPath,
			&i.LikelyNat,
			&i.Temporary,
			&i.FailureReason,
			&i.LastCheckedAt,
			&i.LastSucceededAt,
			&i.LastChangedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeProbeRuns = `-- name: ListNodeProbeRuns :many
SELECT id, node_id, history_generation, configuration_revision, trigger,
       task_id, status, expected_executions,
       started_at, completed_at, received_at
FROM probe_runs
WHERE node_id = ?
ORDER BY started_at DESC, id DESC
LIMIT ?
`

type ListNodeProbeRunsParams struct {
	NodeID string
	Limit  int64
}

func (q *Queries) ListNodeProbeRuns(ctx context.Context, arg ListNodeProbeRunsParams) ([]ProbeRun, error) {
	rows, err := q.db.QueryContext(ctx, listNodeProbeRuns, arg.NodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProbeRun{}
	for rows.Next() {
		var i ProbeRun
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.HistoryGeneration,
			&i.ConfigurationRevision,
			&i.Trigger,
			&i.TaskID,
			&i.Status,
			&i.ExpectedExecutions,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationDeliveries = `-- name: ListNotificationDeliveries :many
SELECT id, event_id, sender_id, sender_name, sender_kind, event_type,
       node_id, egress_id, is_test, status, attempt_count, next_attempt_at,
       last_attempt_at, completed_at, error_code, matched_rule_ids_json,
       event_json, title, body, created_at, updated_at
FROM notification_deliveries
WHERE (?1 = '' OR sender_id = ?1)
  AND (?2 = '' OR status = ?2)
ORDER BY created_at DESC, id DESC
LIMIT ?4 OFFSET ?3
`

type ListNotificationDeliveriesParams struct {
	SenderID       interface{}
	DeliveryStatus interface{}
	PageOffset     int64
	PageSize       int64
}

func (q *Queries) ListNotificationDeliveries(ctx context.Context, arg ListNotificationDeliveriesParams) ([]NotificationDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationDeliveries,
		arg.SenderID,
		arg.DeliveryStatus,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SenderID,
			&i.SenderName,
			&i.SenderKind,
			&i.EventType,
			&i.NodeID,
			&i.EgressID,
			&i.IsTest,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastAttemptAt,
			&i.CompletedAt,
			&i.ErrorCode,
			&i.MatchedRuleIdsJson,
			&i.EventJson,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingNotificationEvents = `-- name: ListPendingNotificationEvents :many
SELECT id, event_type, source_kind, source_id, node_id, egress_id,
       payload_json, observed_at, recorded_at, processed_at
FROM notification_events
WHERE processed_at IS NULL
ORDER BY recorded_at, id
LIMIT ?
`

func (q *Queries) ListPendingNotificationEvents(ctx context.Context, limit int64) ([]NotificationEvent, error) {
	rows, err := q.db.QueryContext(ctx, listPendingNotificationEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationEvent{}
	for rows.Next() {
		var i NotificationEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.SourceKind,
			&i.SourceID,
			&i.NodeID,
			&i.EgressID,
			&i.PayloadJson,
			&i.ObservedAt,
			&i.RecordedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProbeFieldChanges = `-- name: ListProbeFieldChanges :many
SELECT change_set_id, field_id, group_name, json_path, value_type,
       before_value, after_value
FROM probe_field_changes
WHERE change_set_id = ?
ORDER BY group_name, json_path
`

func (q *Queries) ListProbeFieldChanges(ctx context.Context, changeSetID string) ([]ProbeFieldChange, error) {
	rows, err := q.db.QueryContext(ctx, listProbeFieldChanges, changeSetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProbeFieldChange{}
	for rows.Next() {
		var i ProbeFieldChange
		if err := rows.Scan(
			&i.ChangeSetID,
			&i.FieldID,
			&i.GroupName,
			&i.JsonPath,
			&i.ValueType,
			&i.BeforeValue,
			&i.AfterValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProbeRunExecutions = `-- name: ListProbeRunExecutions :many
SELECT id, run_id, egress_id, ordinal, sequence, status, started_at,
       completed_at, failure_stage, diagnostic, received_at
FROM probe_executions
WHERE run_id = ?
ORDER BY ordinal, id
`

func (q *Queries) ListProbeRunExecutions(ctx context.Context, runID string) ([]ProbeExecution, error) {
	rows, err := q.db.QueryContext(ctx, listProbeRunExecutions, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProbeExecution{}
	for rows.Next() {
		var i ProbeExecution
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.EgressID,
			&i.Ordinal,
			&i.Sequence,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.FailureStage,
			&i.Diagnostic,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProbeSnapshots = `-- name: ListProbeSnapshots :many
SELECT s.id, s.execution_id, s.egress_id, s.sequence, s.observed_at,
       s.encoded_size, s.received_at, e.run_id, r.node_id, r.trigger, r.status AS run_status,
       CAST(COALESCE((
           SELECT previous.id
           FROM probe_snapshots previous
           WHERE previous.egress_id = s.egress_id AND previous.sequence < s.sequence
           ORDER BY previous.sequence DESC
           LIMIT 1
       ), '') AS TEXT) AS previous_snapshot_id,
       EXISTS(SELECT 1 FROM probe_snapshot_stars star WHERE star.snapshot_id = s.id) AS starred,
       EXISTS(
           SELECT 1 FROM current_probe_snapshots current_snapshot
           WHERE current_snapshot.snapshot_id = s.id
       ) AS is_current,
       changes.id IS NOT NULL AS processed,
       COALESCE(changes.baseline, 0) AS baseline,
       COALESCE(changes.change_count, 0) AS change_count,
       COALESCE(format.status, 'mismatch') AS format_status,
       COALESCE(format.issue_count, 1) AS format_issue_count
FROM probe_snapshots s
JOIN probe_executions e ON e.id = s.execution_id
JOIN probe_runs r ON r.id = e.run_id
LEFT JOIN probe_change_sets changes ON changes.snapshot_id = s.id
LEFT JOIN probe_snapshot_formats format ON format.snapshot_id = s.id
WHERE (?1 = '' OR r.node_id = ?1)
  AND (?2 = '' OR s.egress_id = ?2)
  AND (?3 IS NULL OR s.observed_at >= ?3)
  AND (?4 IS NULL OR s.observed_at <= ?4)
  AND (?5 = '' OR r.status = ?5)
  AND (?6 = '' OR r.trigger = ?6)
  AND (
      ?7 IS NULL OR
      (COALESCE(changes.change_count, 0) > 0) = ?7
  )
  AND (
      ?8 = '' OR
      COALESCE(format.status, 'mismatch') = ?8
  )
ORDER BY s.observed_at DESC, s.id DESC
LIMIT ?10 OFFSET ?9
`

type ListProbeSnapshotsParams struct {
	NodeID         interface{}
	EgressID       interface{}
	FromObservedAt interface{}
	ToObservedAt   interface{}
	RunStatus      interface{}
	Trigger        interface{}
	Changed        interface{}
	FormatStatus   interface{}
	PageOffset     int64
	PageSize       int64
}

type ListProbeSnapshotsRow struct {
	ID                 string
	ExecutionID        string
	EgressID           string
	Sequence           int64
	ObservedAt         int64
	EncodedSize        int64
	ReceivedAt         int64
	RunID              string
	NodeID             string
	Trigger            string
	RunStatus          string
	PreviousSnapshotID string
	Starred            bool
	IsCurrent          bool
	Processed          bool
	Baseline           int64
	ChangeCount        int64
	FormatStatus       string
	FormatIssueCount   int64
}

func (q *Queries) ListProbeSnapshots(ctx context.Context, arg ListProbeSnapshotsParams) ([]ListProbeSnapshotsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProbeSnapshots,
		arg.NodeID,
		arg.EgressID,
		arg.FromObservedAt,
		arg.ToObservedAt,
		arg.RunStatus,
		arg.Trigger,
		arg.Changed,
		arg.FormatStatus,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProbeSnapshotsRow{}
	for rows.Next() {
		var i ListProbeSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.ExecutionID,
			&i.EgressID,
			&i.Sequence,
			&i.ObservedAt,
			&i.EncodedSize,
			&i.ReceivedAt,
			&i.RunID,
			&i.NodeID,
			&i.Trigger,
			&i.RunStatus,
			&i.PreviousSnapshotID,
			&i.Starred,
			&i.IsCurrent,
			&i.Processed,
			&i.Baseline,
			&i.ChangeCount,
			&i.FormatStatus,
			&i.FormatIssueCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyFixedNotificationDeliveries = `-- name: ListReadyFixedNotificationDeliveries :many
SELECT id, event_id, sender_id, sender_name, sender_kind, event_type,
       node_id, egress_id, is_test, status, attempt_count, next_attempt_at,
       last_attempt_at, completed_at, error_code, matched_rule_ids_json,
       event_json, title, body, created_at, updated_at
FROM notification_deliveries
WHERE sender_kind IN ('telegram', 'webhook')
  AND status IN ('pending', 'retrying')
  AND next_attempt_at <= ?
ORDER BY next_attempt_at, created_at, id
LIMIT ?
`

type ListReadyFixedNotificationDeliveriesParams struct {
	NextAttemptAt *int64
	Limit         int64
}

func (q *Queries) ListReadyFixedNotificationDeliveries(ctx context.Context, arg ListReadyFixedNotificationDeliveriesParams) ([]NotificationDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listReadyFixedNotificationDeliveries, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SenderID,
			&i.SenderName,
			&i.SenderKind,
			&i.EventType,
			&i.NodeID,
			&i.EgressID,
			&i.IsTest,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastAttemptAt,
			&i.CompletedAt,
			&i.ErrorCode,
			&i.MatchedRuleIdsJson,
			&i.EventJson,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadyJavaScriptNotificationDeliveries = `-- name: ListReadyJavaScriptNotificationDeliveries :many
SELECT id, event_id, sender_id, sender_name, sender_kind, event_type,
       node_id, egress_id, is_test, status, attempt_count, next_attempt_at,
       last_attempt_at, completed_at, error_code, matched_rule_ids_json,
       event_json, title, body, created_at, updated_at
FROM notification_deliveries
WHERE sender_kind = 'javascript'
  AND status IN ('pending', 'retrying')
  AND next_attempt_at <= ?
ORDER BY next_attempt_at, created_at, id
LIMIT 1
`

func (q *Queries) ListReadyJavaScriptNotificationDeliveries(ctx context.Context, nextAttemptAt *int64) ([]NotificationDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listReadyJavaScriptNotificationDeliveries, nextAttemptAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.SenderID,
			&i.SenderName,
			&i.SenderKind,
			&i.EventType,
			&i.NodeID,
			&i.EgressID,
			&i.IsTest,
			&i.Status,
			&i.AttemptCount,
			&i.NextAttemptAt,
			&i.LastAttemptAt,
			&i.CompletedAt,
			&i.ErrorCode,
			&i.MatchedRuleIdsJson,
			&i.EventJson,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetentionCandidates = `-- name: ListRetentionCandidates :many
SELECT category, id, observed_at, logical_bytes
FROM (
    SELECT 'execution' AS category, e.id AS id,
           COALESCE(e.completed_at, e.started_at, e.received_at) AS observed_at,
           256 + length(e.id) + length(e.run_id) + length(e.egress_id) +
           COALESCE(length(e.failure_stage), 0) + COALESCE(length(CAST(e.diagnostic AS BLOB)), 0) +
           COALESCE(s.encoded_size + 160, 0) AS logical_bytes
    FROM probe_executions e
    JOIN probe_runs r ON r.id = e.run_id
    LEFT JOIN probe_snapshots s ON s.execution_id = e.id
    WHERE e.status NOT IN ('pending', 'running') AND r.status != 'running'
      AND NOT EXISTS(SELECT 1 FROM probe_snapshot_stars star WHERE star.snapshot_id = s.id)
      AND NOT EXISTS(SELECT 1 FROM current_probe_snapshots current WHERE current.snapshot_id = s.id)
      AND NOT EXISTS(SELECT 1 FROM probe_format_states state WHERE state.snapshot_id = s.id)
      AND NOT EXISTS(
          SELECT 1 FROM probe_comparison_progress progress
          WHERE progress.last_success_snapshot_id = s.id
      )
      AND NOT EXISTS(
          SELECT 1 FROM probe_outcome_states outcome
          WHERE outcome.execution_id = e.id
      )
    UNION ALL
    SELECT 'address-event', id, observed_at,
           256 + length(id) + length(public_address_id) + length(source_path_id) + length(node_id) +
           COALESCE(length(public_address), 0) +
           COALESCE(length(local_interface), 0) + COALESCE(length(local_address), 0) +
           COALESCE(length(proxy_path), 0) + COALESCE(length(failure_reason), 0)
    FROM address_events
    UNION ALL SELECT 'address-gap', id, last_observed_at, 224 FROM history_gaps
    UNION ALL SELECT 'probe-gap', id, last_observed_at, 224 FROM probe_gaps
    UNION ALL
    SELECT 'notification-event', event.id, event.observed_at,
           256 + length(event.id) + length(event.event_type) + length(event.source_kind) +
           length(event.source_id) + COALESCE(length(event.node_id), 0) +
           COALESCE(length(event.egress_id), 0) + length(event.payload_json) +
           COALESCE((
               SELECT SUM(
                   512 + length(delivery.id) + length(delivery.event_id) +
                   length(delivery.sender_id) + length(delivery.sender_name) +
                   length(delivery.sender_kind) + length(delivery.event_type) +
                   length(delivery.matched_rule_ids_json) + length(delivery.event_json) +
                   length(CAST(delivery.title AS BLOB)) + length(CAST(delivery.body AS BLOB)) +
                   COALESCE(length(delivery.error_code), 0)
               )
               FROM notification_deliveries delivery
               WHERE delivery.event_id = event.id
           ), 0)
    FROM notification_events event
    WHERE event.processed_at IS NOT NULL
      AND NOT EXISTS(
          SELECT 1 FROM notification_deliveries delivery
          WHERE delivery.event_id = event.id
            AND delivery.status IN ('pending', 'running', 'retrying')
      )
)
WHERE (?1 IS NULL OR observed_at < ?1)
ORDER BY observed_at, category, id
LIMIT ?2
`

type ListRetentionCandidatesParams struct {
	OlderThan interface{}
	PageSize  int64
}

type ListRetentionCandidatesRow struct {
	Category     string
	ID           string
	ObservedAt   int64
	LogicalBytes int64
}

func (q *Queries) ListRetentionCandidates(ctx context.Context, arg ListRetentionCandidatesParams) ([]ListRetentionCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRetentionCandidates, arg.OlderThan, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRetentionCandidatesRow{}
	for rows.Next() {
		var i ListRetentionCandidatesRow
		if err := rows.Scan(
			&i.Category,
			&i.ID,
			&i.ObservedAt,
			&i.LogicalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationEventProcessed = `-- name: MarkNotificationEventProcessed :execrows
UPDATE notification_events
SET processed_at = ?
WHERE id = ? AND processed_at IS NULL
`

type MarkNotificationEventProcessedParams struct {
	ProcessedAt *int64
	ID          string
}

func (q *Queries) MarkNotificationEventProcessed(ctx context.Context, arg MarkNotificationEventProcessedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNotificationEventProcessed, arg.ProcessedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recoverRunningNotificationDeliveries = `-- name: RecoverRunningNotificationDeliveries :exec
UPDATE notification_deliveries
SET status = CASE WHEN attempt_count >= 4 THEN 'failed' ELSE 'retrying' END,
    next_attempt_at = CASE WHEN attempt_count >= 4 THEN NULL ELSE ? END,
    completed_at = CASE WHEN attempt_count >= 4 THEN ? ELSE NULL END,
    error_code = CASE WHEN attempt_count >= 4 THEN 'center-restarted' ELSE NULL END,
    updated_at = ?
WHERE status = 'running'
`

type RecoverRunningNotificationDeliveriesParams struct {
	NextAttemptAt *int64
	CompletedAt   *int64
	UpdatedAt     int64
}

func (q *Queries) RecoverRunningNotificationDeliveries(ctx context.Context, arg RecoverRunningNotificationDeliveriesParams) error {
	_, err := q.db.ExecContext(ctx, recoverRunningNotificationDeliveries, arg.NextAttemptAt, arg.CompletedAt, arg.UpdatedAt)
	return err
}

const resetAddressGaps = `-- name: ResetAddressGaps :exec
DELETE FROM history_gaps
`

func (q *Queries) ResetAddressGaps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAddressGaps)
	return err
}

const resetAddressHistory = `-- name: ResetAddressHistory :exec
DELETE FROM address_events
`

func (q *Queries) ResetAddressHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAddressHistory)
	return err
}

const resetAddressStates = `-- name: ResetAddressStates :exec
DELETE FROM address_states
`

func (q *Queries) ResetAddressStates(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetAddressStates)
	return err
}

const resetNotificationHistory = `-- name: ResetNotificationHistory :exec
DELETE FROM notification_events
`

func (q *Queries) ResetNotificationHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetNotificationHistory)
	return err
}

const resetProbeComparisonProgress = `-- name: ResetProbeComparisonProgress :exec
DELETE FROM probe_comparison_progress
`

func (q *Queries) ResetProbeComparisonProgress(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetProbeComparisonProgress)
	return err
}

const resetProbeGaps = `-- name: ResetProbeGaps :exec
DELETE FROM probe_gaps
`

func (q *Queries) ResetProbeGaps(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetProbeGaps)
	return err
}

const resetProbeHistory = `-- name: ResetProbeHistory :exec
DELETE FROM probe_runs
`

func (q *Queries) ResetProbeHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetProbeHistory)
	return err
}

const retryNotificationDelivery = `-- name: RetryNotificationDelivery :execrows
UPDATE notification_deliveries
SET status = 'retrying', next_attempt_at = ?, error_code = NULL, updated_at = ?
WHERE id = ? AND status = 'running' AND attempt_count < 4
`

type RetryNotificationDeliveryParams struct {
	NextAttemptAt *int64
	UpdatedAt     int64
	ID            string
}

func (q *Queries) RetryNotificationDelivery(ctx context.Context, arg RetryNotificationDeliveryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retryNotificationDelivery, arg.NextAttemptAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const starProbeSnapshot = `-- name: StarProbeSnapshot :execrows
INSERT INTO probe_snapshot_stars (snapshot_id, starred_at)
VALUES (?, ?)
ON CONFLICT (snapshot_id) DO NOTHING
`

type StarProbeSnapshotParams struct {
	SnapshotID string
	StarredAt  int64
}

func (q *Queries) StarProbeSnapshot(ctx context.Context, arg StarProbeSnapshotParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, starProbeSnapshot, arg.SnapshotID, arg.StarredAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const unstarProbeSnapshot = `-- name: UnstarProbeSnapshot :execrows
DELETE FROM probe_snapshot_stars WHERE snapshot_id = ?
`

func (q *Queries) UnstarProbeSnapshot(ctx context.Context, snapshotID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, unstarProbeSnapshot, snapshotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateHistoryGeneration = `-- name: UpdateHistoryGeneration :execrows
UPDATE history_metadata
SET generation = ?, created_at = ?
WHERE id = 1
`

type UpdateHistoryGenerationParams struct {
	Generation string
	CreatedAt  int64
}

func (q *Queries) UpdateHistoryGeneration(ctx context.Context, arg UpdateHistoryGenerationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateHistoryGeneration, arg.Generation, arg.CreatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProbeExecution = `-- name: UpdateProbeExecution :execrows
UPDATE probe_executions
SET status = ?, started_at = ?, completed_at = ?, failure_stage = ?,
    diagnostic = ?, received_at = ?
WHERE id = ? AND status IN ('pending', 'running')
`

type UpdateProbeExecutionParams struct {
	Status       string
	StartedAt    *int64
	CompletedAt  *int64
	FailureStage *string
	Diagnostic   *string
	ReceivedAt   int64
	ID           string
}

func (q *Queries) UpdateProbeExecution(ctx context.Context, arg UpdateProbeExecutionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateProbeExecution,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.FailureStage,
		arg.Diagnostic,
		arg.ReceivedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertAddressGap = `-- name: UpsertAddressGap :execrows
INSERT INTO history_gaps (
    id, egress_id, node_id, history_generation, kind, dropped_count,
    first_sequence, last_sequence, first_observed_at, last_observed_at,
    received_at
) VALUES (?, ?, ?, ?, 'address', ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    dropped_count = MAX(history_gaps.dropped_count, excluded.dropped_count),
    last_sequence = MAX(history_gaps.last_sequence, excluded.last_sequence),
    last_observed_at = MAX(history_gaps.last_observed_at, excluded.last_observed_at),
    received_at = excluded.received_at
WHERE history_gaps.egress_id = excluded.egress_id
  AND history_gaps.node_id = excluded.node_id
  AND history_gaps.history_generation = excluded.history_generation
  AND history_gaps.first_sequence = excluded.first_sequence
  AND history_gaps.first_observed_at = excluded.first_observed_at
`

type UpsertAddressGapParams struct {
	ID                string
	EgressID          string
	NodeID            string
	HistoryGeneration string
	DroppedCount      int64
	FirstSequence     int64
	LastSequence      int64
	FirstObservedAt   int64
	LastObservedAt    int64
	ReceivedAt        int64
}

func (q *Queries) UpsertAddressGap(ctx context.Context, arg UpsertAddressGapParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertAddressGap,
		arg.ID,
		arg.EgressID,
		arg.NodeID,
		arg.HistoryGeneration,
		arg.DroppedCount,
		arg.FirstSequence,
		arg.LastSequence,
		arg.FirstObservedAt,
		arg.LastObservedAt,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertAddressState = `-- name: UpsertAddressState :exec
INSERT INTO address_states (
    egress_id, node_id, history_generation, family, status, sequence,
    public_address, local_interface, local_address, proxy_path, likely_nat,
    temporary, failure_reason, last_checked_at, last_succeeded_at,
    last_changed_at, received_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (egress_id) DO UPDATE SET
    node_id = excluded.node_id,
    history_generation = excluded.history_generation,
    family = excluded.family,
    status = excluded.status,
    sequence = excluded.sequence,
    public_address = excluded.public_address,
    local_interface = excluded.local_interface,
    local_address = excluded.local_address,
    proxy_path = excluded.proxy_path,
    likely_nat = excluded.likely_nat,
    temporary = excluded.temporary,
    failure_reason = excluded.failure_reason,
    last_checked_at = excluded.last_checked_at,
    last_succeeded_at = excluded.last_succeeded_at,
    last_changed_at = excluded.last_changed_at,
    received_at = excluded.received_at
WHERE excluded.history_generation != address_states.history_generation
   OR excluded.sequence > address_states.sequence
   OR (
       excluded.sequence = address_states.sequence AND
       excluded.last_checked_at >= address_states.last_checked_at
   )
`

type UpsertAddressStateParams struct {
	EgressID          string
	NodeID            string
	HistoryGeneration string
	Family            string
	Status            string
	Sequence          int64
	PublicAddress     *string
	LocalInterface    *string
	LocalAddress      *string
	ProxyPath         int64
	LikelyNat         int64
	Temporary         int64
	FailureReason     *string
	LastCheckedAt     int64
	LastSucceededAt   *int64
	LastChangedAt     *int64
	ReceivedAt        int64
}

func (q *Queries) UpsertAddressState(ctx context.Context, arg UpsertAddressStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertAddressState,
		arg.EgressID,
		arg.NodeID,
		arg.HistoryGeneration,
		arg.Family,
		arg.Status,
		arg.Sequence,
		arg.PublicAddress,
		arg.LocalInterface,
		arg.LocalAddress,
		arg.ProxyPath,
		arg.LikelyNat,
		arg.Temporary,
		arg.FailureReason,
		arg.LastCheckedAt,
		arg.LastSucceededAt,
		arg.LastChangedAt,
		arg.ReceivedAt,
	)
	return err
}

const upsertCurrentProbeSnapshot = `-- name: UpsertCurrentProbeSnapshot :exec
INSERT INTO current_probe_snapshots (
    egress_id, execution_id, snapshot_id, sequence, observed_at, received_at
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (egress_id) DO UPDATE SET
    execution_id = excluded.execution_id,
    snapshot_id = excluded.snapshot_id,
    sequence = excluded.sequence,
    observed_at = excluded.observed_at,
    received_at = excluded.received_at
WHERE excluded.sequence > current_probe_snapshots.sequence
`

type UpsertCurrentProbeSnapshotParams struct {
	EgressID    string
	ExecutionID string
	SnapshotID  string
	Sequence    int64
	ObservedAt  int64
	ReceivedAt  int64
}

func (q *Queries) UpsertCurrentProbeSnapshot(ctx context.Context, arg UpsertCurrentProbeSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertCurrentProbeSnapshot,
		arg.EgressID,
		arg.ExecutionID,
		arg.SnapshotID,
		arg.Sequence,
		arg.ObservedAt,
		arg.ReceivedAt,
	)
	return err
}

const upsertProbeComparisonProgress = `-- name: UpsertProbeComparisonProgress :exec
INSERT INTO probe_comparison_progress (
    egress_id, node_id, history_generation, next_sequence,
    last_success_snapshot_id, updated_at
) VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (egress_id) DO UPDATE SET
    node_id = excluded.node_id,
    history_generation = excluded.history_generation,
    next_sequence = excluded.next_sequence,
    last_success_snapshot_id = excluded.last_success_snapshot_id,
    updated_at = excluded.updated_at
`

type UpsertProbeComparisonProgressParams struct {
	EgressID              string
	NodeID                string
	HistoryGeneration     string
	NextSequence          int64
	LastSuccessSnapshotID *string
	UpdatedAt             int64
}

func (q *Queries) UpsertProbeComparisonProgress(ctx context.Context, arg UpsertProbeComparisonProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertProbeComparisonProgress,
		arg.EgressID,
		arg.NodeID,
		arg.HistoryGeneration,
		arg.NextSequence,
		arg.LastSuccessSnapshotID,
		arg.UpdatedAt,
	)
	return err
}

const upsertProbeFormatState = `-- name: UpsertProbeFormatState :exec
INSERT INTO probe_format_states (
    egress_id, snapshot_id, sequence, status, signature, issue_count,
    issues_json, first_observed_at, last_observed_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (egress_id) DO UPDATE SET
    snapshot_id = excluded.snapshot_id,
    sequence = excluded.sequence,
    status = excluded.status,
    signature = excluded.signature,
    issue_count = excluded.issue_count,
    issues_json = excluded.issues_json,
    first_observed_at = excluded.first_observed_at,
    last_observed_at = excluded.last_observed_at,
    updated_at = excluded.updated_at
WHERE excluded.sequence > probe_format_states.sequence
`

type UpsertProbeFormatStateParams struct {
	EgressID        string
	SnapshotID      string
	Sequence        int64
	Status          string
	Signature       string
	IssueCount      int64
	IssuesJson      []byte
	FirstObservedAt int64
	LastObservedAt  int64
	UpdatedAt       int64
}

func (q *Queries) UpsertProbeFormatState(ctx context.Context, arg UpsertProbeFormatStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertProbeFormatState,
		arg.EgressID,
		arg.SnapshotID,
		arg.Sequence,
		arg.Status,
		arg.Signature,
		arg.IssueCount,
		arg.IssuesJson,
		arg.FirstObservedAt,
		arg.LastObservedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertProbeGap = `-- name: UpsertProbeGap :execrows
INSERT INTO probe_gaps (
    id, egress_id, node_id, history_generation, dropped_count,
    first_sequence, last_sequence, first_observed_at, last_observed_at,
    received_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    dropped_count = MAX(probe_gaps.dropped_count, excluded.dropped_count),
    last_sequence = MAX(probe_gaps.last_sequence, excluded.last_sequence),
    last_observed_at = MAX(probe_gaps.last_observed_at, excluded.last_observed_at),
    received_at = excluded.received_at
WHERE probe_gaps.egress_id = excluded.egress_id
  AND probe_gaps.node_id = excluded.node_id
  AND probe_gaps.history_generation = excluded.history_generation
  AND probe_gaps.first_sequence = excluded.first_sequence
  AND probe_gaps.first_observed_at = excluded.first_observed_at
`

type UpsertProbeGapParams struct {
	ID                string
	EgressID          string
	NodeID            string
	HistoryGeneration string
	DroppedCount      int64
	FirstSequence     int64
	LastSequence      int64
	FirstObservedAt   int64
	LastObservedAt    int64
	ReceivedAt        int64
}

func (q *Queries) UpsertProbeGap(ctx context.Context, arg UpsertProbeGapParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertProbeGap,
		arg.ID,
		arg.EgressID,
		arg.NodeID,
		arg.HistoryGeneration,
		arg.DroppedCount,
		arg.FirstSequence,
		arg.LastSequence,
		arg.FirstObservedAt,
		arg.LastObservedAt,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertProbeOutcomeState = `-- name: UpsertProbeOutcomeState :exec
INSERT INTO probe_outcome_states (
    egress_id, node_id, history_generation, execution_id, sequence,
    status, first_observed_at, last_observed_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (egress_id) DO UPDATE SET
    node_id = excluded.node_id,
    history_generation = excluded.history_generation,
    execution_id = excluded.execution_id,
    sequence = excluded.sequence,
    status = excluded.status,
    first_observed_at = excluded.first_observed_at,
    last_observed_at = excluded.last_observed_at,
    updated_at = excluded.updated_at
WHERE excluded.history_generation != probe_outcome_states.history_generation
   OR excluded.sequence > probe_outcome_states.sequence
`

type UpsertProbeOutcomeStateParams struct {
	EgressID          string
	NodeID            string
	HistoryGeneration string
	ExecutionID       string
	Sequence          int64
	Status            string
	FirstObservedAt   int64
	LastObservedAt    int64
	UpdatedAt         int64
}

func (q *Queries) UpsertProbeOutcomeState(ctx context.Context, arg UpsertProbeOutcomeStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertProbeOutcomeState,
		arg.EgressID,
		arg.NodeID,
		arg.HistoryGeneration,
		arg.ExecutionID,
		arg.Sequence,
		arg.Status,
		arg.FirstObservedAt,
		arg.LastObservedAt,
		arg.UpdatedAt,
	)
	return err
}
