// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package historydb

import (
	"context"
)

const createHistoryMetadata = `-- name: CreateHistoryMetadata :exec
INSERT INTO history_metadata (id, generation, created_at)
VALUES (1, ?, ?)
`

type CreateHistoryMetadataParams struct {
	Generation string
	CreatedAt  int64
}

func (q *Queries) CreateHistoryMetadata(ctx context.Context, arg CreateHistoryMetadataParams) error {
	_, err := q.db.ExecContext(ctx, createHistoryMetadata, arg.Generation, arg.CreatedAt)
	return err
}

const getHistoryMetadata = `-- name: GetHistoryMetadata :one
SELECT id, generation, created_at
FROM history_metadata
WHERE id = 1
`

func (q *Queries) GetHistoryMetadata(ctx context.Context) (HistoryMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getHistoryMetadata)
	var i HistoryMetadatum
	err := row.Scan(&i.ID, &i.Generation, &i.CreatedAt)
	return i, err
}
