/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an administrator session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current administrator session */
        get: operations["getAuthenticatedSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current administrator session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the administrator account */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the administrator username or password */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/api/v1/account/locale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Persist the administrator language preference */
        put: operations["updateAccountLocale"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/totp/enrollment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start TOTP enrollment */
        post: operations["startTOTPEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm and enable TOTP */
        post: operations["confirmTOTPEnrollment"];
        /** Disable TOTP and revoke all sessions */
        delete: operations["disableTOTP"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke every administrator session */
        delete: operations["revokeAllSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read center status */
        get: operations["getSystemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered nodes */
        get: operations["listNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-enrollment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read automatic Agent enrollment settings */
        get: operations["getAgentEnrollment"];
        /** Enable or disable automatic Agent enrollment */
        put: operations["updateAgentEnrollment"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-enrollment/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate or rotate the automatic Agent enrollment key */
        post: operations["rotateAgentEnrollmentKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new Agent and node */
        post: operations["registerAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Agent state and read current control state */
        post: operations["pollAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SupportedLocale: "zh-CN" | "en";
        Account: {
            username: string;
            locale: components["schemas"]["SupportedLocale"];
            usesDefaultCredentials: boolean;
            totpEnabled: boolean;
        };
        AuthenticatedSession: {
            account: components["schemas"]["Account"];
            csrfToken: string;
            /** Format: date-time */
            expiresAt: string;
        };
        LoginRequest: {
            username: string;
            password: string;
            totpCode?: string;
        };
        AccountUpdateRequest: {
            currentPassword: string;
            username?: string;
            newPassword?: string;
        };
        AccountUpdateResult: {
            account: components["schemas"]["Account"];
            sessionRevoked: boolean;
        };
        LocaleUpdateRequest: {
            locale: components["schemas"]["SupportedLocale"];
        };
        CurrentPasswordRequest: {
            currentPassword: string;
        };
        TOTPCodeRequest: {
            code: string;
        };
        DisableTOTPRequest: {
            currentPassword: string;
            code: string;
        };
        TOTPEnrollment: {
            secret: string;
            /** Format: uri */
            provisioningUri: string;
        };
        /** @enum {string} */
        ErrorCode: "invalid_request" | "invalid_credentials" | "totp_required" | "rate_limited" | "unauthenticated" | "csrf_failed" | "origin_not_allowed" | "current_password_invalid" | "invalid_totp" | "totp_already_enabled" | "totp_not_enabled" | "totp_enrollment_not_started" | "no_account_change" | "registration_key_not_initialized" | "registration_key_invalid" | "registration_disabled" | "agent_unauthenticated" | "agent_revoked" | "internal_error";
        ErrorResponse: {
            code: components["schemas"]["ErrorCode"];
            parameters?: {
                [key: string]: string;
            };
        };
        SystemStatus: {
            /** @enum {string} */
            service: "ipchronicle-center";
            /** @enum {string} */
            status: "ok";
            version: string;
            /** Format: int64 */
            configSchemaVersion: number;
            /** Format: int64 */
            historySchemaVersion: number;
            /** @enum {string} */
            transportSecurity: "http" | "https";
            transportWarning: boolean;
            externalOriginConfigured: boolean;
            trustedProxyConfigured: boolean;
        };
        AgentEnrollmentSettings: {
            enabled: boolean;
            hasKey: boolean;
            installationCommand?: string;
            /** Format: date-time */
            rotatedAt?: string;
        };
        AgentEnrollmentUpdate: {
            enabled: boolean;
        };
        /** @enum {string} */
        AgentPlatform: "linux";
        /** @enum {string} */
        AgentArchitecture: "amd64" | "arm64";
        AgentMetadata: {
            hostname: string;
            agentVersion: string;
            operatingSystem: components["schemas"]["AgentPlatform"];
            architecture: components["schemas"]["AgentArchitecture"];
            capabilities: string[];
        };
        AgentRegistrationRequest: {
            registrationKey: string;
            metadata: components["schemas"]["AgentMetadata"];
        };
        AgentRegistrationResult: {
            /** Format: uuid */
            nodeId: string;
            credential: string;
            pollIntervalSeconds: number;
        };
        AgentPollRequest: {
            metadata: components["schemas"]["AgentMetadata"];
            /** Format: int64 */
            appliedConfigurationRevision: number;
            configurationError?: string;
        };
        AgentPollResult: {
            centerVersion: string;
            /** Format: int64 */
            desiredConfigurationRevision: number;
            enabled: boolean;
            pollIntervalSeconds: number;
        };
        /** @enum {string} */
        NodeStatus: "online" | "offline" | "disabled" | "revoked";
        /** @enum {string} */
        NodeConfigurationStatus: "current" | "pending" | "failed";
        Node: {
            /** Format: uuid */
            id: string;
            name: string;
            hostname: string;
            status: components["schemas"]["NodeStatus"];
            enabled: boolean;
            agentVersion: string;
            operatingSystem: components["schemas"]["AgentPlatform"];
            architecture: components["schemas"]["AgentArchitecture"];
            capabilities: string[];
            /** Format: int64 */
            desiredConfigurationRevision: number;
            /** Format: int64 */
            appliedConfigurationRevision: number;
            configurationStatus: components["schemas"]["NodeConfigurationStatus"];
            configurationError?: string;
            /** Format: date-time */
            registeredAt: string;
            /** Format: date-time */
            lastSeenAt?: string;
        };
        NodeList: {
            items: components["schemas"]["Node"][];
        };
    };
    responses: {
        /** @description The request failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication is required or failed. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request failed an origin or CSRF check. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested account transition conflicts with current state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The Agent credential or registration key is invalid. */
        AgentUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Agent registration or authority is disabled or revoked. */
        AgentForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        CSRFToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description The administrator is authenticated. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Login attempts are temporarily throttled. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAuthenticatedSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current session and account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session was revoked. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The administrator account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdateRequest"];
            };
        };
        responses: {
            /** @description The account was updated. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountUpdateResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateAccountLocale: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocaleUpdateRequest"];
            };
        };
        responses: {
            /** @description The account language was updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    startTOTPEnrollment: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurrentPasswordRequest"];
            };
        };
        responses: {
            /** @description One-time TOTP enrollment material. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TOTPEnrollment"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    confirmTOTPEnrollment: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TOTPCodeRequest"];
            };
        };
        responses: {
            /** @description TOTP was enabled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    disableTOTP: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisableTOTPRequest"];
            };
        };
        responses: {
            /** @description TOTP was disabled and all sessions were revoked. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    revokeAllSessions: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every administrator session was revoked. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getSystemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The center is available. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered nodes ordered by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAgentEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current automatic enrollment settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentEnrollmentSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateAgentEnrollment: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentEnrollmentUpdate"];
            };
        };
        responses: {
            /** @description Updated automatic enrollment settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentEnrollmentSettings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    rotateAgentEnrollmentKey: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Automatic enrollment is enabled with a new key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentEnrollmentSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    registerAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRegistrationRequest"];
            };
        };
        responses: {
            /** @description The Agent was registered with a node-specific credential. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRegistrationResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["AgentUnauthorized"];
            403: components["responses"]["AgentForbidden"];
        };
    };
    pollAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentPollRequest"];
            };
        };
        responses: {
            /** @description Current control-plane state for this Agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPollResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["AgentUnauthorized"];
            403: components["responses"]["AgentForbidden"];
        };
    };
}
