/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an administrator session */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current administrator session */
        get: operations["getAuthenticatedSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current administrator session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the administrator account */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change the administrator username or password */
        patch: operations["updateAccount"];
        trace?: never;
    };
    "/api/v1/account/locale": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Persist the administrator language preference */
        put: operations["updateAccountLocale"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/totp/enrollment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start TOTP enrollment */
        post: operations["startTOTPEnrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm and enable TOTP */
        post: operations["confirmTOTPEnrollment"];
        /** Disable TOTP and revoke all sessions */
        delete: operations["disableTOTP"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/account/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke every administrator session */
        delete: operations["revokeAllSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read center status */
        get: operations["getSystemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered nodes */
        get: operations["listNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Permanently delete a node and all owned data */
        delete: operations["deleteNode"];
        options?: never;
        head?: never;
        /** Update node monitoring state */
        patch: operations["updateNode"];
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Permanently revoke a node Agent credential */
        post: operations["revokeNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/sync-session": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start or replace a ten-minute temporary node sync session */
        post: operations["startNodeSyncSession"];
        /** Stop the current temporary node sync session */
        delete: operations["stopNodeSyncSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/network": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        /** Read the latest network inventory, candidates, and configured egresses */
        get: operations["getNodeNetwork"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/egresses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable a discovered interface or source-address egress */
        post: operations["createNodeEgress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/nodes/{nodeId}/egresses/{egressId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
                egressId: components["parameters"]["EgressId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Permanently delete a durable network egress */
        delete: operations["deleteNodeEgress"];
        options?: never;
        head?: never;
        /** Update a durable network egress */
        patch: operations["updateNodeEgress"];
        trace?: never;
    };
    "/api/v1/network-observation-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read global lightweight address discovery services */
        get: operations["getNetworkObservationSettings"];
        /** Replace global lightweight address discovery services */
        put: operations["updateNetworkObservationSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network-proxies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List centrally managed network proxies without revealing passwords */
        get: operations["listNetworkProxies"];
        put?: never;
        /** Create a centrally managed network proxy */
        post: operations["createNetworkProxy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/network-proxies/{proxyId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proxyId: components["parameters"]["ProxyId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Replace network proxy settings and explicitly keep, replace, or clear its password */
        put: operations["updateNetworkProxy"];
        post?: never;
        /** Delete an unreferenced network proxy */
        delete: operations["deleteNetworkProxy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-enrollment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read automatic Agent enrollment settings */
        get: operations["getAgentEnrollment"];
        /** Enable or disable automatic Agent enrollment */
        put: operations["updateAgentEnrollment"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent-enrollment/key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate or rotate the automatic Agent enrollment key */
        post: operations["rotateAgentEnrollmentKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new Agent and node */
        post: operations["registerAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/control": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Agent state and read current control state */
        post: operations["pollAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agent/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current complete desired Agent configuration */
        get: operations["getAgentConfiguration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SupportedLocale: "zh-CN" | "en";
        Account: {
            username: string;
            locale: components["schemas"]["SupportedLocale"];
            usesDefaultCredentials: boolean;
            totpEnabled: boolean;
        };
        AuthenticatedSession: {
            account: components["schemas"]["Account"];
            csrfToken: string;
            /** Format: date-time */
            expiresAt: string;
        };
        LoginRequest: {
            username: string;
            password: string;
            totpCode?: string;
        };
        AccountUpdateRequest: {
            currentPassword: string;
            username?: string;
            newPassword?: string;
        };
        AccountUpdateResult: {
            account: components["schemas"]["Account"];
            sessionRevoked: boolean;
        };
        LocaleUpdateRequest: {
            locale: components["schemas"]["SupportedLocale"];
        };
        CurrentPasswordRequest: {
            currentPassword: string;
        };
        TOTPCodeRequest: {
            code: string;
        };
        DisableTOTPRequest: {
            currentPassword: string;
            code: string;
        };
        TOTPEnrollment: {
            secret: string;
            /** Format: uri */
            provisioningUri: string;
        };
        /** @enum {string} */
        ErrorCode: "invalid_request" | "invalid_credentials" | "totp_required" | "rate_limited" | "unauthenticated" | "csrf_failed" | "origin_not_allowed" | "current_password_invalid" | "invalid_totp" | "totp_already_enabled" | "totp_not_enabled" | "totp_enrollment_not_started" | "no_account_change" | "registration_key_not_initialized" | "registration_key_invalid" | "registration_disabled" | "agent_unauthenticated" | "agent_revoked" | "node_not_found" | "node_revoked" | "node_deletion_pending" | "node_sync_unsupported" | "sync_session_unavailable" | "network_inventory_unavailable" | "invalid_egress_candidate" | "egress_already_exists" | "egress_limit_reached" | "egress_not_found" | "egress_deletion_pending" | "invalid_network_proxy" | "network_proxy_not_found" | "network_proxy_already_exists" | "network_proxy_limit_reached" | "network_proxy_in_use" | "invalid_observation_settings" | "internal_error";
        ErrorResponse: {
            code: components["schemas"]["ErrorCode"];
            parameters?: {
                [key: string]: string;
            };
        };
        SystemStatus: {
            /** @enum {string} */
            service: "ipchronicle-center";
            /** @enum {string} */
            status: "ok";
            version: string;
            /** Format: int64 */
            configSchemaVersion: number;
            /** Format: int64 */
            historySchemaVersion: number;
            /** @enum {string} */
            transportSecurity: "http" | "https";
            transportWarning: boolean;
            externalOriginConfigured: boolean;
            trustedProxyConfigured: boolean;
        };
        AgentEnrollmentSettings: {
            enabled: boolean;
            hasKey: boolean;
            installationCommand?: string;
            /** Format: date-time */
            rotatedAt?: string;
        };
        AgentEnrollmentUpdate: {
            enabled: boolean;
        };
        /** @enum {string} */
        AgentPlatform: "linux";
        /** @enum {string} */
        AgentArchitecture: "amd64" | "arm64";
        AgentMetadata: {
            hostname: string;
            agentVersion: string;
            operatingSystem: components["schemas"]["AgentPlatform"];
            architecture: components["schemas"]["AgentArchitecture"];
            capabilities: string[];
        };
        AgentRegistrationRequest: {
            registrationKey: string;
            metadata: components["schemas"]["AgentMetadata"];
        };
        AgentRegistrationResult: {
            /** Format: uuid */
            nodeId: string;
            credential: string;
            pollIntervalSeconds: number;
        };
        AgentPollRequest: {
            metadata: components["schemas"]["AgentMetadata"];
            /** Format: int64 */
            appliedConfigurationRevision: number;
            configurationError?: string;
            /** Format: int64 */
            configurationErrorRevision?: number;
            networkInventory?: components["schemas"]["NetworkInventory"];
            networkInventoryError?: string;
            addressStates?: components["schemas"]["AgentAddressState"][];
            addressEvents?: components["schemas"]["AgentAddressEvent"][];
            addressGaps?: components["schemas"]["AgentAddressGap"][];
        };
        AgentPollResult: {
            centerVersion: string;
            /** Format: int64 */
            desiredConfigurationRevision: number;
            enabled: boolean;
            pollIntervalSeconds: number;
            syncSession?: components["schemas"]["AgentSyncSession"];
            addressUploadReceipt: components["schemas"]["AgentAddressUploadReceipt"];
        };
        AgentSyncSession: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            expiresAt: string;
            websocketPath: string;
        };
        AgentConfigurationSnapshot: {
            /** @enum {integer} */
            schemaVersion: 4;
            /** Format: int64 */
            revision: number;
            enabled: boolean;
            historyGeneration: string;
            discoveryServices: components["schemas"]["NetworkObservationSettingsUpdate"];
            egresses: components["schemas"]["AgentEgressConfiguration"][];
            proxies: components["schemas"]["AgentProxyConfiguration"][];
        };
        /** @enum {string} */
        AddressFamily: "ipv4" | "ipv6";
        NetworkInterface: {
            name: string;
            index: number;
            up: boolean;
            loopback: boolean;
        };
        /** @enum {string} */
        NetworkAddressScope: "global" | "private" | "shared" | "unique-local" | "link-local" | "loopback" | "multicast" | "unspecified" | "other";
        NetworkAddress: {
            interfaceName: string;
            address: string;
            prefixLength: number;
            family: components["schemas"]["AddressFamily"];
            scope: components["schemas"]["NetworkAddressScope"];
            temporary: boolean;
            tentative: boolean;
            deprecated: boolean;
            duplicate: boolean;
        };
        NetworkRoute: {
            interfaceName: string;
            family: components["schemas"]["AddressFamily"];
            destination: string;
            gateway?: string;
            /** Format: int64 */
            metric: number;
            default: boolean;
        };
        NetworkInventory: {
            /** Format: date-time */
            capturedAt: string;
            interfaces: components["schemas"]["NetworkInterface"][];
            addresses: components["schemas"]["NetworkAddress"][];
            routes: components["schemas"]["NetworkRoute"][];
        };
        /** @enum {string} */
        NetworkEgressKind: "default" | "interface" | "source" | "proxy";
        NetworkEgress: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            nodeId: string;
            name: string;
            kind: components["schemas"]["NetworkEgressKind"];
            family: components["schemas"]["AddressFamily"];
            interfaceName?: string;
            sourceAddress?: string;
            /** Format: uuid */
            proxyId?: string;
            enabled: boolean;
            available: boolean;
            automatic: boolean;
            /** Format: int64 */
            lightweightIntervalSeconds: number;
            probeOnAddressChange: boolean;
            deletionStatus?: components["schemas"]["EgressDeletionStatus"];
            deletionError?: string;
        };
        /** @enum {string} */
        EgressDeletionStatus: "pending" | "failed";
        EgressDeletion: {
            /** Format: uuid */
            egressId: string;
            /** Format: uuid */
            nodeId: string;
            status: components["schemas"]["EgressDeletionStatus"];
            /** Format: date-time */
            requestedAt: string;
            error?: string;
        };
        NetworkEgressCandidate: {
            /** @enum {string} */
            kind: "interface" | "source";
            family: components["schemas"]["AddressFamily"];
            interfaceName: string;
            sourceAddress?: string;
            scope?: components["schemas"]["NetworkAddressScope"];
            temporary: boolean;
            eligible: boolean;
            /** @enum {string} */
            unavailableReason?: "interface-down" | "no-usable-route" | "temporary-address" | "unusable-address";
            /** Format: uuid */
            configuredEgressId?: string;
        };
        NodeNetworkState: {
            inventory?: components["schemas"]["NetworkInventory"];
            inventoryError?: string;
            /** Format: date-time */
            inventoryReceivedAt?: string;
            egresses: components["schemas"]["NetworkEgress"][];
            candidates: components["schemas"]["NetworkEgressCandidate"][];
            addressStates: components["schemas"]["AgentAddressState"][];
            addressEvents: components["schemas"]["AgentAddressEvent"][];
            addressGaps: components["schemas"]["AgentAddressGap"][];
        };
        NetworkEgressCreate: {
            /** @enum {string} */
            kind: "interface" | "source" | "proxy";
            family: components["schemas"]["AddressFamily"];
            interfaceName?: string;
            sourceAddress?: string;
            /** Format: uuid */
            proxyId?: string;
        };
        NetworkEgressUpdate: {
            enabled: boolean;
            /** Format: int64 */
            lightweightIntervalSeconds: number;
            probeOnAddressChange: boolean;
        };
        AgentEgressConfiguration: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["NetworkEgressKind"];
            family: components["schemas"]["AddressFamily"];
            interfaceName?: string;
            sourceAddress?: string;
            /** Format: uuid */
            proxyId?: string;
            enabled: boolean;
            /** Format: int64 */
            lightweightIntervalSeconds: number;
            probeOnAddressChange: boolean;
        };
        /** @enum {string} */
        NetworkProxyScheme: "http" | "https" | "socks5";
        NetworkProxy: {
            /** Format: uuid */
            id: string;
            name: string;
            scheme: components["schemas"]["NetworkProxyScheme"];
            host: string;
            /** Format: int64 */
            port: number;
            username?: string;
            passwordConfigured: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        NetworkProxyList: {
            items: components["schemas"]["NetworkProxy"][];
        };
        NetworkProxyCreate: {
            name: string;
            scheme: components["schemas"]["NetworkProxyScheme"];
            host: string;
            /** Format: int64 */
            port: number;
            username?: string;
            password?: string;
        };
        /** @enum {string} */
        NetworkProxyPasswordAction: "keep" | "replace" | "clear";
        NetworkProxyUpdate: {
            name: string;
            scheme: components["schemas"]["NetworkProxyScheme"];
            host: string;
            /** Format: int64 */
            port: number;
            username?: string;
            passwordAction: components["schemas"]["NetworkProxyPasswordAction"];
            password?: string;
        };
        AgentProxyConfiguration: {
            /** Format: uuid */
            id: string;
            scheme: components["schemas"]["NetworkProxyScheme"];
            host: string;
            /** Format: int64 */
            port: number;
            username?: string;
            password?: string;
        };
        NetworkObservationSettings: {
            ipv4Services: components["schemas"]["DiscoveryServiceList"];
            ipv6Services: components["schemas"]["DiscoveryServiceList"];
            /** Format: date-time */
            updatedAt: string;
        };
        NetworkObservationSettingsUpdate: {
            ipv4Services: components["schemas"]["DiscoveryServiceList"];
            ipv6Services: components["schemas"]["DiscoveryServiceList"];
        };
        DiscoveryServiceList: string[];
        /** @enum {string} */
        AddressObservationStatus: "confirmed" | "failed";
        /** @enum {string} */
        AddressFailureReason: "selector-unavailable" | "no-valid-response" | "confirmation-unavailable" | "conflicting-responses";
        /** @enum {string} */
        AddressEventKind: "first-observation" | "address-change" | "check-failure" | "recovery";
        AgentAddressState: {
            /** Format: uuid */
            egressId: string;
            historyGeneration: string;
            family: components["schemas"]["AddressFamily"];
            status: components["schemas"]["AddressObservationStatus"];
            /** Format: int64 */
            sequence: number;
            publicAddress?: string;
            localInterface?: string;
            localAddress?: string;
            proxyPath: boolean;
            likelyNat: boolean;
            temporary: boolean;
            failureReason?: components["schemas"]["AddressFailureReason"];
            /** Format: date-time */
            lastCheckedAt: string;
            /** Format: date-time */
            lastSucceededAt?: string;
            /** Format: date-time */
            lastChangedAt?: string;
        };
        AgentAddressEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            egressId: string;
            historyGeneration: string;
            /** Format: int64 */
            sequence: number;
            kind: components["schemas"]["AddressEventKind"];
            family: components["schemas"]["AddressFamily"];
            previousAddress?: string;
            publicAddress?: string;
            localInterface?: string;
            localAddress?: string;
            proxyPath: boolean;
            likelyNat: boolean;
            temporary: boolean;
            failureReason?: components["schemas"]["AddressFailureReason"];
            /** Format: date-time */
            observedAt: string;
        };
        AgentAddressGap: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            egressId: string;
            historyGeneration: string;
            /** Format: int64 */
            droppedCount: number;
            /** Format: int64 */
            firstSequence: number;
            /** Format: int64 */
            lastSequence: number;
            /** Format: date-time */
            firstObservedAt: string;
            /** Format: date-time */
            lastObservedAt: string;
        };
        AgentAddressGapReceipt: {
            /** Format: uuid */
            id: string;
            /** Format: int64 */
            lastSequence: number;
        };
        AgentAddressUploadReceipt: {
            acceptedEventIds: string[];
            discardedEventIds: string[];
            acceptedGaps: components["schemas"]["AgentAddressGapReceipt"][];
            discardedGaps: components["schemas"]["AgentAddressGapReceipt"][];
        };
        /** @enum {string} */
        NodeStatus: "online" | "offline" | "disabled" | "revoked";
        /** @enum {string} */
        NodeConfigurationStatus: "current" | "pending" | "failed";
        /** @enum {string} */
        NodeDeletionStatus: "pending" | "failed";
        /** @enum {string} */
        NodeSyncStatus: "pending" | "connected" | "degraded";
        NodeUpdate: {
            enabled: boolean;
        };
        NodeDeletion: {
            /** Format: uuid */
            nodeId: string;
            status: components["schemas"]["NodeDeletionStatus"];
            /** Format: date-time */
            requestedAt: string;
            error?: string;
        };
        Node: {
            /** Format: uuid */
            id: string;
            name: string;
            hostname: string;
            status: components["schemas"]["NodeStatus"];
            enabled: boolean;
            agentVersion: string;
            operatingSystem: components["schemas"]["AgentPlatform"];
            architecture: components["schemas"]["AgentArchitecture"];
            capabilities: string[];
            /** Format: int64 */
            desiredConfigurationRevision: number;
            /** Format: int64 */
            appliedConfigurationRevision: number;
            configurationStatus: components["schemas"]["NodeConfigurationStatus"];
            configurationError?: string;
            deletionStatus?: components["schemas"]["NodeDeletionStatus"];
            deletionError?: string;
            syncStatus?: components["schemas"]["NodeSyncStatus"];
            /** Format: date-time */
            syncExpiresAt?: string;
            /** Format: date-time */
            registeredAt: string;
            /** Format: date-time */
            lastSeenAt?: string;
        };
        NodeList: {
            items: components["schemas"]["Node"][];
        };
    };
    responses: {
        /** @description The request failed validation. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication is required or failed. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request failed an origin or CSRF check. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested state transition conflicts with current state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The Agent credential or registration key is invalid. */
        AgentUnauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Agent registration or authority is disabled or revoked. */
        AgentForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        CSRFToken: string;
        NodeId: string;
        EgressId: string;
        ProxyId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description The administrator is authenticated. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedSession"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description Login attempts are temporarily throttled. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAuthenticatedSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current session and account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session was revoked. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The administrator account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateAccount: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountUpdateRequest"];
            };
        };
        responses: {
            /** @description The account was updated. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountUpdateResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    updateAccountLocale: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocaleUpdateRequest"];
            };
        };
        responses: {
            /** @description The account language was updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    startTOTPEnrollment: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CurrentPasswordRequest"];
            };
        };
        responses: {
            /** @description One-time TOTP enrollment material. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TOTPEnrollment"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    confirmTOTPEnrollment: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TOTPCodeRequest"];
            };
        };
        responses: {
            /** @description TOTP was enabled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    disableTOTP: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisableTOTPRequest"];
            };
        };
        responses: {
            /** @description TOTP was disabled and all sessions were revoked. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    revokeAllSessions: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every administrator session was revoked. */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getSystemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The center is available. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listNodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered nodes ordered by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteNode: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Durable node deletion has been queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDeletion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateNode: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NodeUpdate"];
            };
        };
        responses: {
            /** @description The node was updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    revokeNode: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Agent credential was revoked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    startNodeSyncSession: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The temporary sync session was started. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    stopNodeSyncSession: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The temporary sync session is stopped. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Node"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getNodeNetwork: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current network state for the node. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeNetworkState"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createNodeEgress: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path: {
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NetworkEgressCreate"];
            };
        };
        responses: {
            /** @description The durable egress was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkEgress"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteNodeEgress: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path: {
                nodeId: components["parameters"]["NodeId"];
                egressId: components["parameters"]["EgressId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Durable egress deletion has been queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EgressDeletion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateNodeEgress: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path: {
                nodeId: components["parameters"]["NodeId"];
                egressId: components["parameters"]["EgressId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NetworkEgressUpdate"];
            };
        };
        responses: {
            /** @description The egress was updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkEgress"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getNetworkObservationSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current lightweight address discovery settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkObservationSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateNetworkObservationSettings: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NetworkObservationSettingsUpdate"];
            };
        };
        responses: {
            /** @description Lightweight address discovery settings were updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkObservationSettings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listNetworkProxies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Network proxies ordered by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkProxyList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createNetworkProxy: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NetworkProxyCreate"];
            };
        };
        responses: {
            /** @description The network proxy was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkProxy"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    updateNetworkProxy: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path: {
                proxyId: components["parameters"]["ProxyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NetworkProxyUpdate"];
            };
        };
        responses: {
            /** @description The network proxy was updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkProxy"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    deleteNetworkProxy: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path: {
                proxyId: components["parameters"]["ProxyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The network proxy was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getAgentEnrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current automatic enrollment settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentEnrollmentSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateAgentEnrollment: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentEnrollmentUpdate"];
            };
        };
        responses: {
            /** @description Updated automatic enrollment settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentEnrollmentSettings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    rotateAgentEnrollmentKey: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: components["parameters"]["CSRFToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Automatic enrollment is enabled with a new key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentEnrollmentSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    registerAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentRegistrationRequest"];
            };
        };
        responses: {
            /** @description The Agent was registered with a node-specific credential. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRegistrationResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["AgentUnauthorized"];
            403: components["responses"]["AgentForbidden"];
        };
    };
    pollAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentPollRequest"];
            };
        };
        responses: {
            /** @description Current control-plane state for this Agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPollResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["AgentUnauthorized"];
            403: components["responses"]["AgentForbidden"];
        };
    };
    getAgentConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current complete desired configuration snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentConfigurationSnapshot"];
                };
            };
            401: components["responses"]["AgentUnauthorized"];
            403: components["responses"]["AgentForbidden"];
        };
    };
}
