services:
  center:
    image: ghcr.io/ipchronicle/ipchronicle-center:latest
    restart: unless-stopped
    environment:
      IPCHRONICLE_ADMIN_USERNAME: ${IPCHRONICLE_ADMIN_USERNAME:-admin}
      IPCHRONICLE_ADMIN_PASSWORD: ${IPCHRONICLE_ADMIN_PASSWORD:-admin}
    ports:
      - "${IPCHRONICLE_HTTP_PORT:-8080}:8080"
    volumes:
      - ./data/config:/var/lib/ipchronicle/config
      - ./data/history:/var/lib/ipchronicle/history
