// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package logsdb

type LogEvent struct {
	ID                    string
	Source                string
	NodeID                *string
	OccurredAt            int64
	ReceivedAt            int64
	Level                 string
	Component             string
	EventType             string
	Message               string
	PublicAddressID       *string
	PublicAddress         *string
	Family                *string
	TaskID                *string
	ProxyID               *string
	ConfigurationRevision *int64
	DiscoveryPath         *string
	FailureCategory       *string
	RequestMethod         *string
	RequestTarget         *string
	HttpStatus            *int64
	DurationMilliseconds  *int64
	ResponseContentType   *string
	RateLimitHeaders      *string
	ResponseBody          []byte
	ResponseTruncated     int64
	DroppedCount          *int64
	DroppedFrom           *int64
	DroppedTo             *int64
	LogicalBytes          int64
}
