// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package logsdb

import (
	"context"
)

const countLogEvents = `-- name: CountLogEvents :one
SELECT COUNT(*) FROM log_events
`

func (q *Queries) CountLogEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLogEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLogEventsOlderThan = `-- name: DeleteLogEventsOlderThan :execrows
DELETE FROM log_events WHERE id IN (
  SELECT candidate.id FROM log_events AS candidate
  WHERE candidate.occurred_at < ?
  ORDER BY candidate.occurred_at, candidate.id
  LIMIT ?
)
`

type DeleteLogEventsOlderThanParams struct {
	OccurredAt int64
	Limit      int64
}

func (q *Queries) DeleteLogEventsOlderThan(ctx context.Context, arg DeleteLogEventsOlderThanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLogEventsOlderThan, arg.OccurredAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteOldestLogEvents = `-- name: DeleteOldestLogEvents :execrows
DELETE FROM log_events WHERE id IN (
  SELECT candidate.id FROM log_events AS candidate
  ORDER BY candidate.occurred_at, candidate.id
  LIMIT ?
)
`

func (q *Queries) DeleteOldestLogEvents(ctx context.Context, limit int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOldestLogEvents, limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLogEvent = `-- name: GetLogEvent :one
SELECT id, source, node_id, occurred_at, received_at, level, component, event_type, message, public_address_id, public_address, family, task_id, proxy_id, configuration_revision, discovery_path, failure_category, request_method, request_target, http_status, duration_milliseconds, response_content_type, rate_limit_headers, response_body, response_truncated, dropped_count, dropped_from, dropped_to, logical_bytes FROM log_events WHERE id = ?
`

func (q *Queries) GetLogEvent(ctx context.Context, id string) (LogEvent, error) {
	row := q.db.QueryRowContext(ctx, getLogEvent, id)
	var i LogEvent
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.NodeID,
		&i.OccurredAt,
		&i.ReceivedAt,
		&i.Level,
		&i.Component,
		&i.EventType,
		&i.Message,
		&i.PublicAddressID,
		&i.PublicAddress,
		&i.Family,
		&i.TaskID,
		&i.ProxyID,
		&i.ConfigurationRevision,
		&i.DiscoveryPath,
		&i.FailureCategory,
		&i.RequestMethod,
		&i.RequestTarget,
		&i.HttpStatus,
		&i.DurationMilliseconds,
		&i.ResponseContentType,
		&i.RateLimitHeaders,
		&i.ResponseBody,
		&i.ResponseTruncated,
		&i.DroppedCount,
		&i.DroppedFrom,
		&i.DroppedTo,
		&i.LogicalBytes,
	)
	return i, err
}

const insertLogEvent = `-- name: InsertLogEvent :execrows
INSERT INTO log_events(
  id, source, node_id, occurred_at, received_at, level, component, event_type,
  message, public_address_id, public_address, family, task_id, proxy_id,
  configuration_revision, discovery_path, failure_category, request_method,
  request_target, http_status, duration_milliseconds, response_content_type,
  rate_limit_headers, response_body, response_truncated, dropped_count,
  dropped_from, dropped_to, logical_bytes
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO NOTHING
`

type InsertLogEventParams struct {
	ID                    string
	Source                string
	NodeID                *string
	OccurredAt            int64
	ReceivedAt            int64
	Level                 string
	Component             string
	EventType             string
	Message               string
	PublicAddressID       *string
	PublicAddress         *string
	Family                *string
	TaskID                *string
	ProxyID               *string
	ConfigurationRevision *int64
	DiscoveryPath         *string
	FailureCategory       *string
	RequestMethod         *string
	RequestTarget         *string
	HttpStatus            *int64
	DurationMilliseconds  *int64
	ResponseContentType   *string
	RateLimitHeaders      *string
	ResponseBody          []byte
	ResponseTruncated     int64
	DroppedCount          *int64
	DroppedFrom           *int64
	DroppedTo             *int64
	LogicalBytes          int64
}

func (q *Queries) InsertLogEvent(ctx context.Context, arg InsertLogEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertLogEvent,
		arg.ID,
		arg.Source,
		arg.NodeID,
		arg.OccurredAt,
		arg.ReceivedAt,
		arg.Level,
		arg.Component,
		arg.EventType,
		arg.Message,
		arg.PublicAddressID,
		arg.PublicAddress,
		arg.Family,
		arg.TaskID,
		arg.ProxyID,
		arg.ConfigurationRevision,
		arg.DiscoveryPath,
		arg.FailureCategory,
		arg.RequestMethod,
		arg.RequestTarget,
		arg.HttpStatus,
		arg.DurationMilliseconds,
		arg.ResponseContentType,
		arg.RateLimitHeaders,
		arg.ResponseBody,
		arg.ResponseTruncated,
		arg.DroppedCount,
		arg.DroppedFrom,
		arg.DroppedTo,
		arg.LogicalBytes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listLogEvents = `-- name: ListLogEvents :many
SELECT id, source, node_id, occurred_at, received_at, level, component,
       event_type, message, public_address_id, public_address, family,
       task_id, proxy_id, configuration_revision, failure_category,
       request_method, request_target, http_status, duration_milliseconds,
       response_content_type,
       CAST(COALESCE(length(response_body), 0) AS INTEGER) AS response_body_bytes,
       response_truncated, dropped_count,
       dropped_from, dropped_to, logical_bytes
FROM log_events
WHERE (?1 IS NULL OR occurred_at >= ?1)
  AND (?2 IS NULL OR occurred_at <= ?2)
  AND (?3 IS NULL OR node_id = ?3)
  AND (?4 IS NULL OR level = ?4)
  AND (?5 IS NULL OR component = ?5)
  AND (?6 IS NULL OR event_type = ?6)
  AND (?7 IS NULL OR public_address = ?7)
  AND (?8 IS NULL OR task_id = ?8)
  AND (?9 IS NULL OR proxy_id = ?9)
  AND (?10 IS NULL OR instr(message, ?10) > 0)
  AND (?11 IS NULL OR occurred_at < ?11
       OR (occurred_at = ?11 AND id < ?12))
ORDER BY occurred_at DESC, id DESC
LIMIT ?13
`

type ListLogEventsParams struct {
	FromTime      interface{}
	ToTime        interface{}
	NodeID        interface{}
	Level         interface{}
	Component     interface{}
	EventType     interface{}
	PublicAddress interface{}
	TaskID        interface{}
	ProxyID       interface{}
	Keyword       interface{}
	CursorTime    interface{}
	CursorID      *string
	PageSize      int64
}

type ListLogEventsRow struct {
	ID                    string
	Source                string
	NodeID                *string
	OccurredAt            int64
	ReceivedAt            int64
	Level                 string
	Component             string
	EventType             string
	Message               string
	PublicAddressID       *string
	PublicAddress         *string
	Family                *string
	TaskID                *string
	ProxyID               *string
	ConfigurationRevision *int64
	FailureCategory       *string
	RequestMethod         *string
	RequestTarget         *string
	HttpStatus            *int64
	DurationMilliseconds  *int64
	ResponseContentType   *string
	ResponseBodyBytes     int64
	ResponseTruncated     int64
	DroppedCount          *int64
	DroppedFrom           *int64
	DroppedTo             *int64
	LogicalBytes          int64
}

func (q *Queries) ListLogEvents(ctx context.Context, arg ListLogEventsParams) ([]ListLogEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLogEvents,
		arg.FromTime,
		arg.ToTime,
		arg.NodeID,
		arg.Level,
		arg.Component,
		arg.EventType,
		arg.PublicAddress,
		arg.TaskID,
		arg.ProxyID,
		arg.Keyword,
		arg.CursorTime,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLogEventsRow{}
	for rows.Next() {
		var i ListLogEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.NodeID,
			&i.OccurredAt,
			&i.ReceivedAt,
			&i.Level,
			&i.Component,
			&i.EventType,
			&i.Message,
			&i.PublicAddressID,
			&i.PublicAddress,
			&i.Family,
			&i.TaskID,
			&i.ProxyID,
			&i.ConfigurationRevision,
			&i.FailureCategory,
			&i.RequestMethod,
			&i.RequestTarget,
			&i.HttpStatus,
			&i.DurationMilliseconds,
			&i.ResponseContentType,
			&i.ResponseBodyBytes,
			&i.ResponseTruncated,
			&i.DroppedCount,
			&i.DroppedFrom,
			&i.DroppedTo,
			&i.LogicalBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOldestLogEventSizes = `-- name: ListOldestLogEventSizes :many
SELECT logical_bytes
FROM log_events
ORDER BY occurred_at, id
LIMIT ?
`

func (q *Queries) ListOldestLogEventSizes(ctx context.Context, limit int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listOldestLogEventSizes, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var logical_bytes int64
		if err := rows.Scan(&logical_bytes); err != nil {
			return nil, err
		}
		items = append(items, logical_bytes)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumLogLogicalBytes = `-- name: SumLogLogicalBytes :one
SELECT CAST(COALESCE(SUM(logical_bytes), 0) AS INTEGER) FROM log_events
`

func (q *Queries) SumLogLogicalBytes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumLogLogicalBytes)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
