#!/usr/bin/env bash
set -euo pipefail

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root_dir"

git diff --exit-code -- \
  internal/generated/api/server.gen.go \
  internal/generated/agentapi/client.gen.go \
  web/src/api/schema.d.ts

grep -Fq "Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT" internal/generated/api/server.gen.go
grep -Fq "Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT" internal/generated/agentapi/client.gen.go
grep -Fq "This file was auto-generated by openapi-typescript" web/src/api/schema.d.ts
