// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package configdb

type Administrator struct {
	ID                     int64
	Username               string
	PasswordHash           string
	Locale                 string
	UsesDefaultCredentials int64
	TotpSecretEncrypted    []byte
	TotpEnabled            int64
	TotpLastUsedStep       int64
	CreatedAt              int64
	CredentialsUpdatedAt   int64
}

type AdministratorSession struct {
	TokenDigest   []byte
	CreatedAt     int64
	ExpiresAt     int64
	ClientAddress string
	UserAgent     string
}

type AgentEnrollment struct {
	ID           int64
	Enabled      int64
	KeyDigest    []byte
	KeyEncrypted []byte
	CreatedAt    int64
	RotatedAt    int64
}

type Node struct {
	ID                           string
	Name                         string
	Hostname                     string
	CredentialDigest             []byte
	Enabled                      int64
	RevokedAt                    *int64
	AgentVersion                 string
	OperatingSystem              string
	Architecture                 string
	DesiredConfigurationRevision int64
	AppliedConfigurationRevision int64
	ConfigurationError           *string
	RegisteredAt                 int64
	LastSeenAt                   *int64
	ConfigurationErrorRevision   *int64
}

type NodeCapability struct {
	NodeID     string
	Capability string
}

type NodeDeletionOperation struct {
	NodeID           string
	CredentialDigest []byte
	Status           string
	RequestedAt      int64
	UpdatedAt        int64
	LastError        *string
}

type NodeSyncSession struct {
	NodeID      string
	SessionID   string
	RequestedAt int64
	ExpiresAt   int64
	DeliveredAt *int64
}

type RevokedAgentCredential struct {
	CredentialDigest []byte
	RevokedAt        int64
	Reason           string
}

type SystemState struct {
	ID                       int64
	HistoryGeneration        string
	PendingHistoryGeneration *string
	HistoryResetAt           *int64
}
