// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package configdb

type Administrator struct {
	ID                     int64
	Username               string
	PasswordHash           string
	Locale                 string
	UsesDefaultCredentials int64
	TotpSecretEncrypted    []byte
	TotpEnabled            int64
	TotpLastUsedStep       int64
	CreatedAt              int64
	CredentialsUpdatedAt   int64
}

type AdministratorSession struct {
	TokenDigest   []byte
	CreatedAt     int64
	ExpiresAt     int64
	ClientAddress string
	UserAgent     string
}

type AgentEnrollment struct {
	ID           int64
	Enabled      int64
	KeyDigest    []byte
	KeyEncrypted []byte
	CreatedAt    int64
	RotatedAt    int64
}

type EgressDeletionOperation struct {
	EgressID    string
	NodeID      string
	Status      string
	RequestedAt int64
	UpdatedAt   int64
	LastError   *string
}

type HistoryRetentionSetting struct {
	ID                      int64
	Mode                    string
	MaxAgeDays              *int64
	MaxLogicalBytes         *int64
	UpdatedAt               int64
	LastCleanupAt           *int64
	LastCleanupDeletedItems int64
	LastCleanupError        *string
}

type NetworkEgress struct {
	ID                         string
	NodeID                     string
	Name                       string
	Kind                       string
	Family                     string
	InterfaceName              *string
	SourceAddress              *string
	ProxyID                    *string
	Enabled                    int64
	Available                  int64
	Automatic                  int64
	LightweightIntervalSeconds int64
	ProbeOnAddressChange       int64
	CreatedAt                  int64
	UpdatedAt                  int64
}

type NetworkObservationSetting struct {
	ID           int64
	Ipv4Services string
	Ipv6Services string
	UpdatedAt    int64
}

type NetworkProxy struct {
	ID                string
	Name              string
	Scheme            string
	Host              string
	Port              int64
	Username          *string
	PasswordEncrypted []byte
	CreatedAt         int64
	UpdatedAt         int64
}

type Node struct {
	ID                           string
	Name                         string
	Hostname                     string
	CredentialDigest             []byte
	Enabled                      int64
	RevokedAt                    *int64
	AgentVersion                 string
	OperatingSystem              string
	Architecture                 string
	DesiredConfigurationRevision int64
	AppliedConfigurationRevision int64
	ConfigurationError           *string
	RegisteredAt                 int64
	LastSeenAt                   *int64
	ConfigurationErrorRevision   *int64
	PhysicalMemoryBytes          *int64
	ProbeScheduleEnabled         int64
	ProbeScheduleCron            string
	ProbeScheduleTimezone        string
	ProbeLowMemoryOverride       int64
	AgentRevision                *string
}

type NodeCapability struct {
	NodeID     string
	Capability string
}

type NodeDeletionOperation struct {
	NodeID           string
	CredentialDigest []byte
	Status           string
	RequestedAt      int64
	UpdatedAt        int64
	LastError        *string
}

type NodeNetworkInventory struct {
	NodeID     string
	Payload    *string
	CapturedAt *int64
	ReceivedAt int64
	LastError  *string
}

type NodeProbeStatus struct {
	NodeID                            string
	ActiveRunID                       *string
	NextScheduledAt                   *int64
	LastOccurrenceAt                  *int64
	LastOccurrenceTrigger             *string
	LastOccurrenceStatus              *string
	LastSkipReason                    *string
	HistoryResetGeneration            *string
	HistoryResetAt                    *int64
	HistoryResetDiscardedAddressItems int64
	HistoryResetDiscardedProbeItems   int64
	ReportedAt                        int64
}

type NodeSyncSession struct {
	NodeID      string
	SessionID   string
	RequestedAt int64
	ExpiresAt   int64
	DeliveredAt *int64
}

type NotificationRule struct {
	ID        string
	Name      string
	Enabled   int64
	SenderID  string
	EventType string
	FieldID   *string
	NodeID    *string
	EgressID  *string
	CreatedAt int64
	UpdatedAt int64
}

type NotificationSender struct {
	ID                     string
	Name                   string
	Kind                   string
	Enabled                int64
	ConfigurationEncrypted []byte
	CreatedAt              int64
	UpdatedAt              int64
}

type PendingPublicAddressProbe struct {
	NodeID                        string
	PublicAddressID               string
	RequiredConfigurationRevision int64
	CreatedAt                     int64
}

type ProbeTask struct {
	ID                        string
	NodeID                    string
	Kind                      string
	Status                    string
	CreatedAt                 int64
	ExpiresAt                 int64
	AcknowledgedAt            *int64
	StartedAt                 *int64
	CompletedAt               *int64
	RunID                     *string
	RejectionReason           *string
	TargetVersion             *string
	PreviousVersion           *string
	ResultVersion             *string
	FailureCode               *string
	Diagnostic                *string
	TerminalConfirmedAt       *int64
	Trigger                   string
	TriggeringPublicAddressID *string
}

type PublicAddress struct {
	ID                 string
	Address            string
	Family             string
	ProbeEnabled       int64
	ProbeOnRediscovery int64
	SelectedPathID     *string
	FirstSeenAt        int64
	LastSeenAt         int64
	UpdatedAt          int64
}

type PublicAddressNode struct {
	PublicAddressID string
	NodeID          string
	FirstSeenAt     int64
	LastSeenAt      int64
}

type PublicAddressPath struct {
	PublicAddressID string
	PathID          string
	NodeID          string
	LocalInterface  *string
	LocalAddress    *string
	ProxyPath       int64
	LikelyNat       int64
	Temporary       int64
	Available       int64
	LastCheckedAt   int64
	LastSucceededAt *int64
}

type RevokedAgentCredential struct {
	CredentialDigest []byte
	RevokedAt        int64
	Reason           string
}

type SystemState struct {
	ID                       int64
	HistoryGeneration        string
	PendingHistoryGeneration *string
	HistoryResetAt           *int64
	ReleaseChannel           string
	ExternalOrigin           string
}
