// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package configdb

type Administrator struct {
	ID                     int64
	Username               string
	PasswordHash           string
	Locale                 string
	UsesDefaultCredentials int64
	TotpSecretEncrypted    []byte
	TotpEnabled            int64
	TotpLastUsedStep       int64
	CreatedAt              int64
	CredentialsUpdatedAt   int64
}

type AdministratorSession struct {
	TokenDigest   []byte
	CreatedAt     int64
	ExpiresAt     int64
	ClientAddress string
	UserAgent     string
}

type SystemState struct {
	ID                       int64
	HistoryGeneration        string
	PendingHistoryGeneration *string
	HistoryResetAt           *int64
}
