// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package configdb

import (
	"context"
)

const completeNodeDeletion = `-- name: CompleteNodeDeletion :exec
UPDATE node_deletion_operations
SET status = 'completed', updated_at = ?, last_error = NULL
WHERE node_id = ?
`

type CompleteNodeDeletionParams struct {
	UpdatedAt int64
	NodeID    string
}

func (q *Queries) CompleteNodeDeletion(ctx context.Context, arg CompleteNodeDeletionParams) error {
	_, err := q.db.ExecContext(ctx, completeNodeDeletion, arg.UpdatedAt, arg.NodeID)
	return err
}

const createAdministrator = `-- name: CreateAdministrator :exec
INSERT INTO administrators (
    id, username, password_hash, locale, uses_default_credentials,
    created_at, credentials_updated_at
) VALUES (1, ?, ?, ?, ?, ?, ?)
`

type CreateAdministratorParams struct {
	Username               string
	PasswordHash           string
	Locale                 string
	UsesDefaultCredentials int64
	CreatedAt              int64
	CredentialsUpdatedAt   int64
}

func (q *Queries) CreateAdministrator(ctx context.Context, arg CreateAdministratorParams) error {
	_, err := q.db.ExecContext(ctx, createAdministrator,
		arg.Username,
		arg.PasswordHash,
		arg.Locale,
		arg.UsesDefaultCredentials,
		arg.CreatedAt,
		arg.CredentialsUpdatedAt,
	)
	return err
}

const createAdministratorSession = `-- name: CreateAdministratorSession :exec
INSERT INTO administrator_sessions (
    token_digest, created_at, expires_at, client_address, user_agent
) VALUES (?, ?, ?, ?, ?)
`

type CreateAdministratorSessionParams struct {
	TokenDigest   []byte
	CreatedAt     int64
	ExpiresAt     int64
	ClientAddress string
	UserAgent     string
}

func (q *Queries) CreateAdministratorSession(ctx context.Context, arg CreateAdministratorSessionParams) error {
	_, err := q.db.ExecContext(ctx, createAdministratorSession,
		arg.TokenDigest,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ClientAddress,
		arg.UserAgent,
	)
	return err
}

const createNode = `-- name: CreateNode :exec
INSERT INTO nodes (
    id, name, hostname, credential_digest, agent_version,
    operating_system, architecture, desired_configuration_revision, registered_at
) VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?)
`

type CreateNodeParams struct {
	ID               string
	Name             string
	Hostname         string
	CredentialDigest []byte
	AgentVersion     string
	OperatingSystem  string
	Architecture     string
	RegisteredAt     int64
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) error {
	_, err := q.db.ExecContext(ctx, createNode,
		arg.ID,
		arg.Name,
		arg.Hostname,
		arg.CredentialDigest,
		arg.AgentVersion,
		arg.OperatingSystem,
		arg.Architecture,
		arg.RegisteredAt,
	)
	return err
}

const createNodeCapability = `-- name: CreateNodeCapability :exec
INSERT INTO node_capabilities (node_id, capability)
VALUES (?, ?)
`

type CreateNodeCapabilityParams struct {
	NodeID     string
	Capability string
}

func (q *Queries) CreateNodeCapability(ctx context.Context, arg CreateNodeCapabilityParams) error {
	_, err := q.db.ExecContext(ctx, createNodeCapability, arg.NodeID, arg.Capability)
	return err
}

const createNodeDeletion = `-- name: CreateNodeDeletion :exec
INSERT INTO node_deletion_operations (
    node_id, credential_digest, status, requested_at, updated_at
) VALUES (?, ?, 'pending', ?, ?)
ON CONFLICT (node_id) DO UPDATE SET
    status = CASE
        WHEN node_deletion_operations.status = 'completed' THEN 'completed'
        ELSE 'pending'
    END,
    updated_at = excluded.updated_at,
    last_error = NULL
`

type CreateNodeDeletionParams struct {
	NodeID           string
	CredentialDigest []byte
	RequestedAt      int64
	UpdatedAt        int64
}

func (q *Queries) CreateNodeDeletion(ctx context.Context, arg CreateNodeDeletionParams) error {
	_, err := q.db.ExecContext(ctx, createNodeDeletion,
		arg.NodeID,
		arg.CredentialDigest,
		arg.RequestedAt,
		arg.UpdatedAt,
	)
	return err
}

const createNodeEgress = `-- name: CreateNodeEgress :exec
INSERT INTO network_egresses (
    id, node_id, name, kind, family, interface_name, source_address,
    enabled, available, automatic, lightweight_interval_seconds,
    probe_on_address_change, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateNodeEgressParams struct {
	ID                         string
	NodeID                     string
	Name                       string
	Kind                       string
	Family                     string
	InterfaceName              *string
	SourceAddress              *string
	Enabled                    int64
	Available                  int64
	Automatic                  int64
	LightweightIntervalSeconds int64
	ProbeOnAddressChange       int64
	CreatedAt                  int64
	UpdatedAt                  int64
}

func (q *Queries) CreateNodeEgress(ctx context.Context, arg CreateNodeEgressParams) error {
	_, err := q.db.ExecContext(ctx, createNodeEgress,
		arg.ID,
		arg.NodeID,
		arg.Name,
		arg.Kind,
		arg.Family,
		arg.InterfaceName,
		arg.SourceAddress,
		arg.Enabled,
		arg.Available,
		arg.Automatic,
		arg.LightweightIntervalSeconds,
		arg.ProbeOnAddressChange,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createSystemState = `-- name: CreateSystemState :exec
INSERT INTO system_state (id, history_generation)
VALUES (1, ?)
`

func (q *Queries) CreateSystemState(ctx context.Context, historyGeneration string) error {
	_, err := q.db.ExecContext(ctx, createSystemState, historyGeneration)
	return err
}

const deleteAdministratorSession = `-- name: DeleteAdministratorSession :exec
DELETE FROM administrator_sessions
WHERE token_digest = ?
`

func (q *Queries) DeleteAdministratorSession(ctx context.Context, tokenDigest []byte) error {
	_, err := q.db.ExecContext(ctx, deleteAdministratorSession, tokenDigest)
	return err
}

const deleteAllAdministratorSessions = `-- name: DeleteAllAdministratorSessions :exec
DELETE FROM administrator_sessions
`

func (q *Queries) DeleteAllAdministratorSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAdministratorSessions)
	return err
}

const deleteExpiredAdministratorSessions = `-- name: DeleteExpiredAdministratorSessions :exec
DELETE FROM administrator_sessions
WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredAdministratorSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAdministratorSessions, expiresAt)
	return err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes
WHERE id = ?
`

func (q *Queries) DeleteNode(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNode, id)
	return err
}

const deleteNodeCapabilities = `-- name: DeleteNodeCapabilities :exec
DELETE FROM node_capabilities
WHERE node_id = ?
`

func (q *Queries) DeleteNodeCapabilities(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeCapabilities, nodeID)
	return err
}

const deleteNodeEgress = `-- name: DeleteNodeEgress :execrows
DELETE FROM network_egresses
WHERE id = ? AND node_id = ?
`

type DeleteNodeEgressParams struct {
	ID     string
	NodeID string
}

func (q *Queries) DeleteNodeEgress(ctx context.Context, arg DeleteNodeEgressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNodeEgress, arg.ID, arg.NodeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteNodeSyncSession = `-- name: DeleteNodeSyncSession :exec
DELETE FROM node_sync_sessions
WHERE node_id = ?
`

func (q *Queries) DeleteNodeSyncSession(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeSyncSession, nodeID)
	return err
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE administrators
SET totp_secret_encrypted = NULL, totp_enabled = 0,
    totp_last_used_step = -1
WHERE id = 1
`

func (q *Queries) DisableTOTP(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, disableTOTP)
	return err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE administrators
SET totp_enabled = 1, totp_last_used_step = ?
WHERE id = 1 AND totp_secret_encrypted IS NOT NULL
`

func (q *Queries) EnableTOTP(ctx context.Context, totpLastUsedStep int64) error {
	_, err := q.db.ExecContext(ctx, enableTOTP, totpLastUsedStep)
	return err
}

const failNodeDeletion = `-- name: FailNodeDeletion :exec
UPDATE node_deletion_operations
SET status = 'failed', updated_at = ?, last_error = ?
WHERE node_id = ? AND status != 'completed'
`

type FailNodeDeletionParams struct {
	UpdatedAt int64
	LastError *string
	NodeID    string
}

func (q *Queries) FailNodeDeletion(ctx context.Context, arg FailNodeDeletionParams) error {
	_, err := q.db.ExecContext(ctx, failNodeDeletion, arg.UpdatedAt, arg.LastError, arg.NodeID)
	return err
}

const getActiveNodeSyncSession = `-- name: GetActiveNodeSyncSession :one
SELECT node_id, session_id, requested_at, expires_at, delivered_at
FROM node_sync_sessions
WHERE node_id = ? AND expires_at > ?
`

type GetActiveNodeSyncSessionParams struct {
	NodeID    string
	ExpiresAt int64
}

func (q *Queries) GetActiveNodeSyncSession(ctx context.Context, arg GetActiveNodeSyncSessionParams) (NodeSyncSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveNodeSyncSession, arg.NodeID, arg.ExpiresAt)
	var i NodeSyncSession
	err := row.Scan(
		&i.NodeID,
		&i.SessionID,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getActiveNodeSyncSessionByID = `-- name: GetActiveNodeSyncSessionByID :one
SELECT node_id, session_id, requested_at, expires_at, delivered_at
FROM node_sync_sessions
WHERE node_id = ? AND session_id = ? AND expires_at > ?
`

type GetActiveNodeSyncSessionByIDParams struct {
	NodeID    string
	SessionID string
	ExpiresAt int64
}

func (q *Queries) GetActiveNodeSyncSessionByID(ctx context.Context, arg GetActiveNodeSyncSessionByIDParams) (NodeSyncSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveNodeSyncSessionByID, arg.NodeID, arg.SessionID, arg.ExpiresAt)
	var i NodeSyncSession
	err := row.Scan(
		&i.NodeID,
		&i.SessionID,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getAdministrator = `-- name: GetAdministrator :one
SELECT id, username, password_hash, locale, uses_default_credentials,
       totp_secret_encrypted, totp_enabled, totp_last_used_step,
       created_at, credentials_updated_at
FROM administrators
WHERE id = 1
`

func (q *Queries) GetAdministrator(ctx context.Context) (Administrator, error) {
	row := q.db.QueryRowContext(ctx, getAdministrator)
	var i Administrator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Locale,
		&i.UsesDefaultCredentials,
		&i.TotpSecretEncrypted,
		&i.TotpEnabled,
		&i.TotpLastUsedStep,
		&i.CreatedAt,
		&i.CredentialsUpdatedAt,
	)
	return i, err
}

const getAdministratorByUsername = `-- name: GetAdministratorByUsername :one
SELECT id, username, password_hash, locale, uses_default_credentials,
       totp_secret_encrypted, totp_enabled, totp_last_used_step,
       created_at, credentials_updated_at
FROM administrators
WHERE username = ? COLLATE NOCASE
`

func (q *Queries) GetAdministratorByUsername(ctx context.Context, username string) (Administrator, error) {
	row := q.db.QueryRowContext(ctx, getAdministratorByUsername, username)
	var i Administrator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Locale,
		&i.UsesDefaultCredentials,
		&i.TotpSecretEncrypted,
		&i.TotpEnabled,
		&i.TotpLastUsedStep,
		&i.CreatedAt,
		&i.CredentialsUpdatedAt,
	)
	return i, err
}

const getAdministratorSession = `-- name: GetAdministratorSession :one
SELECT token_digest, created_at, expires_at, client_address, user_agent
FROM administrator_sessions
WHERE token_digest = ? AND expires_at > ?
`

type GetAdministratorSessionParams struct {
	TokenDigest []byte
	ExpiresAt   int64
}

func (q *Queries) GetAdministratorSession(ctx context.Context, arg GetAdministratorSessionParams) (AdministratorSession, error) {
	row := q.db.QueryRowContext(ctx, getAdministratorSession, arg.TokenDigest, arg.ExpiresAt)
	var i AdministratorSession
	err := row.Scan(
		&i.TokenDigest,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClientAddress,
		&i.UserAgent,
	)
	return i, err
}

const getAgentEnrollment = `-- name: GetAgentEnrollment :one
SELECT id, enabled, key_digest, key_encrypted, created_at, rotated_at
FROM agent_enrollment
WHERE id = 1
`

func (q *Queries) GetAgentEnrollment(ctx context.Context) (AgentEnrollment, error) {
	row := q.db.QueryRowContext(ctx, getAgentEnrollment)
	var i AgentEnrollment
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.KeyDigest,
		&i.KeyEncrypted,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const getDefaultNodeEgress = `-- name: GetDefaultNodeEgress :one
SELECT id, node_id, name, kind, family, interface_name, source_address,
       enabled, available, automatic, lightweight_interval_seconds,
       probe_on_address_change, created_at, updated_at
FROM network_egresses
WHERE node_id = ? AND kind = 'default' AND family = ?
`

type GetDefaultNodeEgressParams struct {
	NodeID string
	Family string
}

func (q *Queries) GetDefaultNodeEgress(ctx context.Context, arg GetDefaultNodeEgressParams) (NetworkEgress, error) {
	row := q.db.QueryRowContext(ctx, getDefaultNodeEgress, arg.NodeID, arg.Family)
	var i NetworkEgress
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Kind,
		&i.Family,
		&i.InterfaceName,
		&i.SourceAddress,
		&i.Enabled,
		&i.Available,
		&i.Automatic,
		&i.LightweightIntervalSeconds,
		&i.ProbeOnAddressChange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeByCredentialDigest = `-- name: GetNodeByCredentialDigest :one
SELECT id, name, hostname, credential_digest, enabled, revoked_at,
       agent_version, operating_system, architecture,
       desired_configuration_revision, applied_configuration_revision,
       configuration_error, registered_at, last_seen_at,
       configuration_error_revision
FROM nodes
WHERE credential_digest = ?
`

func (q *Queries) GetNodeByCredentialDigest(ctx context.Context, credentialDigest []byte) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByCredentialDigest, credentialDigest)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CredentialDigest,
		&i.Enabled,
		&i.RevokedAt,
		&i.AgentVersion,
		&i.OperatingSystem,
		&i.Architecture,
		&i.DesiredConfigurationRevision,
		&i.AppliedConfigurationRevision,
		&i.ConfigurationError,
		&i.RegisteredAt,
		&i.LastSeenAt,
		&i.ConfigurationErrorRevision,
	)
	return i, err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, name, hostname, credential_digest, enabled, revoked_at,
       agent_version, operating_system, architecture,
       desired_configuration_revision, applied_configuration_revision,
       configuration_error, registered_at, last_seen_at,
       configuration_error_revision
FROM nodes
WHERE id = ?
`

func (q *Queries) GetNodeByID(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CredentialDigest,
		&i.Enabled,
		&i.RevokedAt,
		&i.AgentVersion,
		&i.OperatingSystem,
		&i.Architecture,
		&i.DesiredConfigurationRevision,
		&i.AppliedConfigurationRevision,
		&i.ConfigurationError,
		&i.RegisteredAt,
		&i.LastSeenAt,
		&i.ConfigurationErrorRevision,
	)
	return i, err
}

const getNodeCapability = `-- name: GetNodeCapability :one
SELECT capability
FROM node_capabilities
WHERE node_id = ? AND capability = ?
`

type GetNodeCapabilityParams struct {
	NodeID     string
	Capability string
}

func (q *Queries) GetNodeCapability(ctx context.Context, arg GetNodeCapabilityParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getNodeCapability, arg.NodeID, arg.Capability)
	var capability string
	err := row.Scan(&capability)
	return capability, err
}

const getNodeDeletion = `-- name: GetNodeDeletion :one
SELECT node_id, credential_digest, status, requested_at, updated_at, last_error
FROM node_deletion_operations
WHERE node_id = ?
`

func (q *Queries) GetNodeDeletion(ctx context.Context, nodeID string) (NodeDeletionOperation, error) {
	row := q.db.QueryRowContext(ctx, getNodeDeletion, nodeID)
	var i NodeDeletionOperation
	err := row.Scan(
		&i.NodeID,
		&i.CredentialDigest,
		&i.Status,
		&i.RequestedAt,
		&i.UpdatedAt,
		&i.LastError,
	)
	return i, err
}

const getNodeEgress = `-- name: GetNodeEgress :one
SELECT id, node_id, name, kind, family, interface_name, source_address,
       enabled, available, automatic, lightweight_interval_seconds,
       probe_on_address_change, created_at, updated_at
FROM network_egresses
WHERE node_id = ? AND id = ?
`

type GetNodeEgressParams struct {
	NodeID string
	ID     string
}

func (q *Queries) GetNodeEgress(ctx context.Context, arg GetNodeEgressParams) (NetworkEgress, error) {
	row := q.db.QueryRowContext(ctx, getNodeEgress, arg.NodeID, arg.ID)
	var i NetworkEgress
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Kind,
		&i.Family,
		&i.InterfaceName,
		&i.SourceAddress,
		&i.Enabled,
		&i.Available,
		&i.Automatic,
		&i.LightweightIntervalSeconds,
		&i.ProbeOnAddressChange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeEgressBySelector = `-- name: GetNodeEgressBySelector :one
SELECT id, node_id, name, kind, family, interface_name, source_address,
       enabled, available, automatic, lightweight_interval_seconds,
       probe_on_address_change, created_at, updated_at
FROM network_egresses
WHERE node_id = ? AND kind = ? AND family = ? AND interface_name = ?
  AND COALESCE(source_address, '') = COALESCE(?, '')
`

type GetNodeEgressBySelectorParams struct {
	NodeID        string
	Kind          string
	Family        string
	InterfaceName *string
	SourceAddress *string
}

func (q *Queries) GetNodeEgressBySelector(ctx context.Context, arg GetNodeEgressBySelectorParams) (NetworkEgress, error) {
	row := q.db.QueryRowContext(ctx, getNodeEgressBySelector,
		arg.NodeID,
		arg.Kind,
		arg.Family,
		arg.InterfaceName,
		arg.SourceAddress,
	)
	var i NetworkEgress
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Name,
		&i.Kind,
		&i.Family,
		&i.InterfaceName,
		&i.SourceAddress,
		&i.Enabled,
		&i.Available,
		&i.Automatic,
		&i.LightweightIntervalSeconds,
		&i.ProbeOnAddressChange,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeNetworkInventory = `-- name: GetNodeNetworkInventory :one
SELECT node_id, payload, captured_at, received_at, last_error
FROM node_network_inventories
WHERE node_id = ?
`

func (q *Queries) GetNodeNetworkInventory(ctx context.Context, nodeID string) (NodeNetworkInventory, error) {
	row := q.db.QueryRowContext(ctx, getNodeNetworkInventory, nodeID)
	var i NodeNetworkInventory
	err := row.Scan(
		&i.NodeID,
		&i.Payload,
		&i.CapturedAt,
		&i.ReceivedAt,
		&i.LastError,
	)
	return i, err
}

const getRevokedAgentCredential = `-- name: GetRevokedAgentCredential :one
SELECT credential_digest, revoked_at, reason
FROM revoked_agent_credentials
WHERE credential_digest = ?
`

func (q *Queries) GetRevokedAgentCredential(ctx context.Context, credentialDigest []byte) (RevokedAgentCredential, error) {
	row := q.db.QueryRowContext(ctx, getRevokedAgentCredential, credentialDigest)
	var i RevokedAgentCredential
	err := row.Scan(&i.CredentialDigest, &i.RevokedAt, &i.Reason)
	return i, err
}

const getSystemState = `-- name: GetSystemState :one
SELECT id, history_generation, pending_history_generation, history_reset_at
FROM system_state
WHERE id = 1
`

func (q *Queries) GetSystemState(ctx context.Context) (SystemState, error) {
	row := q.db.QueryRowContext(ctx, getSystemState)
	var i SystemState
	err := row.Scan(
		&i.ID,
		&i.HistoryGeneration,
		&i.PendingHistoryGeneration,
		&i.HistoryResetAt,
	)
	return i, err
}

const incrementAllNodeDesiredConfigurationRevisions = `-- name: IncrementAllNodeDesiredConfigurationRevisions :exec
UPDATE nodes
SET desired_configuration_revision = desired_configuration_revision + 1,
    configuration_error = NULL,
    configuration_error_revision = NULL
WHERE revoked_at IS NULL
`

func (q *Queries) IncrementAllNodeDesiredConfigurationRevisions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, incrementAllNodeDesiredConfigurationRevisions)
	return err
}

const incrementNodeDesiredConfigurationRevision = `-- name: IncrementNodeDesiredConfigurationRevision :execrows
UPDATE nodes
SET desired_configuration_revision = desired_configuration_revision + 1,
    configuration_error = NULL,
    configuration_error_revision = NULL
WHERE id = ? AND revoked_at IS NULL
`

func (q *Queries) IncrementNodeDesiredConfigurationRevision(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, incrementNodeDesiredConfigurationRevision, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listActiveNodeDeletions = `-- name: ListActiveNodeDeletions :many
SELECT node_id, credential_digest, status, requested_at, updated_at, last_error
FROM node_deletion_operations
WHERE status IN ('pending', 'failed')
ORDER BY requested_at, node_id
LIMIT ?
`

func (q *Queries) ListActiveNodeDeletions(ctx context.Context, limit int64) ([]NodeDeletionOperation, error) {
	rows, err := q.db.QueryContext(ctx, listActiveNodeDeletions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeDeletionOperation{}
	for rows.Next() {
		var i NodeDeletionOperation
		if err := rows.Scan(
			&i.NodeID,
			&i.CredentialDigest,
			&i.Status,
			&i.RequestedAt,
			&i.UpdatedAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeCapabilities = `-- name: ListNodeCapabilities :many
SELECT node_id, capability
FROM node_capabilities
ORDER BY node_id, capability
`

func (q *Queries) ListNodeCapabilities(ctx context.Context) ([]NodeCapability, error) {
	rows, err := q.db.QueryContext(ctx, listNodeCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeCapability{}
	for rows.Next() {
		var i NodeCapability
		if err := rows.Scan(&i.NodeID, &i.Capability); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeEgresses = `-- name: ListNodeEgresses :many
SELECT id, node_id, name, kind, family, interface_name, source_address,
       enabled, available, automatic, lightweight_interval_seconds,
       probe_on_address_change, created_at, updated_at
FROM network_egresses
WHERE node_id = ?
ORDER BY family, kind, created_at, id
`

func (q *Queries) ListNodeEgresses(ctx context.Context, nodeID string) ([]NetworkEgress, error) {
	rows, err := q.db.QueryContext(ctx, listNodeEgresses, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetworkEgress{}
	for rows.Next() {
		var i NetworkEgress
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Name,
			&i.Kind,
			&i.Family,
			&i.InterfaceName,
			&i.SourceAddress,
			&i.Enabled,
			&i.Available,
			&i.Automatic,
			&i.LightweightIntervalSeconds,
			&i.ProbeOnAddressChange,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeSyncSessions = `-- name: ListNodeSyncSessions :many
SELECT node_id, session_id, requested_at, expires_at, delivered_at
FROM node_sync_sessions
WHERE expires_at > ?
ORDER BY node_id
`

func (q *Queries) ListNodeSyncSessions(ctx context.Context, expiresAt int64) ([]NodeSyncSession, error) {
	rows, err := q.db.QueryContext(ctx, listNodeSyncSessions, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeSyncSession{}
	for rows.Next() {
		var i NodeSyncSession
		if err := rows.Scan(
			&i.NodeID,
			&i.SessionID,
			&i.RequestedAt,
			&i.ExpiresAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, hostname, credential_digest, enabled, revoked_at,
       agent_version, operating_system, architecture,
       desired_configuration_revision, applied_configuration_revision,
       configuration_error, registered_at, last_seen_at,
       configuration_error_revision
FROM nodes
ORDER BY name COLLATE NOCASE, id
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.CredentialDigest,
			&i.Enabled,
			&i.RevokedAt,
			&i.AgentVersion,
			&i.OperatingSystem,
			&i.Architecture,
			&i.DesiredConfigurationRevision,
			&i.AppliedConfigurationRevision,
			&i.ConfigurationError,
			&i.RegisteredAt,
			&i.LastSeenAt,
			&i.ConfigurationErrorRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNodeSyncSessionDelivered = `-- name: MarkNodeSyncSessionDelivered :execrows
UPDATE node_sync_sessions
SET delivered_at = COALESCE(delivered_at, ?)
WHERE node_id = ? AND session_id = ? AND expires_at > ?
`

type MarkNodeSyncSessionDeliveredParams struct {
	DeliveredAt *int64
	NodeID      string
	SessionID   string
	ExpiresAt   int64
}

func (q *Queries) MarkNodeSyncSessionDelivered(ctx context.Context, arg MarkNodeSyncSessionDeliveredParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markNodeSyncSessionDelivered,
		arg.DeliveredAt,
		arg.NodeID,
		arg.SessionID,
		arg.ExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const promotePendingHistoryGeneration = `-- name: PromotePendingHistoryGeneration :execrows
UPDATE system_state
SET history_generation = pending_history_generation,
    pending_history_generation = NULL,
    history_reset_at = ?
WHERE id = 1 AND pending_history_generation = ?
`

type PromotePendingHistoryGenerationParams struct {
	HistoryResetAt           *int64
	PendingHistoryGeneration *string
}

func (q *Queries) PromotePendingHistoryGeneration(ctx context.Context, arg PromotePendingHistoryGenerationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, promotePendingHistoryGeneration, arg.HistoryResetAt, arg.PendingHistoryGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordNodeNetworkInventoryError = `-- name: RecordNodeNetworkInventoryError :exec
INSERT INTO node_network_inventories (
    node_id, payload, captured_at, received_at, last_error
) VALUES (?, NULL, NULL, ?, ?)
ON CONFLICT (node_id) DO UPDATE SET
    received_at = excluded.received_at,
    last_error = excluded.last_error
`

type RecordNodeNetworkInventoryErrorParams struct {
	NodeID     string
	ReceivedAt int64
	LastError  *string
}

func (q *Queries) RecordNodeNetworkInventoryError(ctx context.Context, arg RecordNodeNetworkInventoryErrorParams) error {
	_, err := q.db.ExecContext(ctx, recordNodeNetworkInventoryError, arg.NodeID, arg.ReceivedAt, arg.LastError)
	return err
}

const rehashAdministratorPassword = `-- name: RehashAdministratorPassword :exec
UPDATE administrators
SET password_hash = ?
WHERE id = 1
`

func (q *Queries) RehashAdministratorPassword(ctx context.Context, passwordHash string) error {
	_, err := q.db.ExecContext(ctx, rehashAdministratorPassword, passwordHash)
	return err
}

const retryNodeDeletion = `-- name: RetryNodeDeletion :exec
UPDATE node_deletion_operations
SET status = 'pending', updated_at = ?, last_error = NULL
WHERE node_id = ? AND status = 'failed'
`

type RetryNodeDeletionParams struct {
	UpdatedAt int64
	NodeID    string
}

func (q *Queries) RetryNodeDeletion(ctx context.Context, arg RetryNodeDeletionParams) error {
	_, err := q.db.ExecContext(ctx, retryNodeDeletion, arg.UpdatedAt, arg.NodeID)
	return err
}

const revokeNode = `-- name: RevokeNode :execrows
UPDATE nodes
SET enabled = 0, revoked_at = ?, configuration_error = NULL,
    configuration_error_revision = NULL
WHERE id = ? AND revoked_at IS NULL
`

type RevokeNodeParams struct {
	RevokedAt *int64
	ID        string
}

func (q *Queries) RevokeNode(ctx context.Context, arg RevokeNodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeNode, arg.RevokedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAgentEnrollmentEnabled = `-- name: SetAgentEnrollmentEnabled :execrows
UPDATE agent_enrollment
SET enabled = ?
WHERE id = 1
`

func (q *Queries) SetAgentEnrollmentEnabled(ctx context.Context, enabled int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAgentEnrollmentEnabled, enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setNodeEgressAvailability = `-- name: SetNodeEgressAvailability :execrows
UPDATE network_egresses
SET available = ?, updated_at = ?
WHERE id = ? AND node_id = ? AND available != ?
`

type SetNodeEgressAvailabilityParams struct {
	Available   int64
	UpdatedAt   int64
	ID          string
	NodeID      string
	Available_2 int64
}

func (q *Queries) SetNodeEgressAvailability(ctx context.Context, arg SetNodeEgressAvailabilityParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setNodeEgressAvailability,
		arg.Available,
		arg.UpdatedAt,
		arg.ID,
		arg.NodeID,
		arg.Available_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setNodeEgressEnabled = `-- name: SetNodeEgressEnabled :execrows
UPDATE network_egresses
SET enabled = ?, updated_at = ?
WHERE id = ? AND node_id = ? AND enabled != ?
`

type SetNodeEgressEnabledParams struct {
	Enabled   int64
	UpdatedAt int64
	ID        string
	NodeID    string
	Enabled_2 int64
}

func (q *Queries) SetNodeEgressEnabled(ctx context.Context, arg SetNodeEgressEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setNodeEgressEnabled,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
		arg.NodeID,
		arg.Enabled_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setNodeEnabled = `-- name: SetNodeEnabled :execrows
UPDATE nodes
SET enabled = ?,
    desired_configuration_revision = desired_configuration_revision + 1,
    configuration_error = NULL,
    configuration_error_revision = NULL
WHERE id = ? AND enabled != ? AND revoked_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM node_deletion_operations
      WHERE node_id = nodes.id AND status != 'completed'
  )
`

type SetNodeEnabledParams struct {
	Enabled   int64
	ID        string
	Enabled_2 int64
}

func (q *Queries) SetNodeEnabled(ctx context.Context, arg SetNodeEnabledParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setNodeEnabled, arg.Enabled, arg.ID, arg.Enabled_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setPendingHistoryGeneration = `-- name: SetPendingHistoryGeneration :exec
UPDATE system_state
SET pending_history_generation = ?
WHERE id = 1 AND pending_history_generation IS NULL
`

func (q *Queries) SetPendingHistoryGeneration(ctx context.Context, pendingHistoryGeneration *string) error {
	_, err := q.db.ExecContext(ctx, setPendingHistoryGeneration, pendingHistoryGeneration)
	return err
}

const setTOTPEnrollment = `-- name: SetTOTPEnrollment :exec
UPDATE administrators
SET totp_secret_encrypted = ?, totp_enabled = 0,
    totp_last_used_step = -1
WHERE id = 1
`

func (q *Queries) SetTOTPEnrollment(ctx context.Context, totpSecretEncrypted []byte) error {
	_, err := q.db.ExecContext(ctx, setTOTPEnrollment, totpSecretEncrypted)
	return err
}

const updateAdministratorLocale = `-- name: UpdateAdministratorLocale :exec
UPDATE administrators
SET locale = ?
WHERE id = 1
`

func (q *Queries) UpdateAdministratorLocale(ctx context.Context, locale string) error {
	_, err := q.db.ExecContext(ctx, updateAdministratorLocale, locale)
	return err
}

const updateAdministratorPassword = `-- name: UpdateAdministratorPassword :exec
UPDATE administrators
SET password_hash = ?, uses_default_credentials = ?,
    credentials_updated_at = ?
WHERE id = 1
`

type UpdateAdministratorPasswordParams struct {
	PasswordHash           string
	UsesDefaultCredentials int64
	CredentialsUpdatedAt   int64
}

func (q *Queries) UpdateAdministratorPassword(ctx context.Context, arg UpdateAdministratorPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateAdministratorPassword, arg.PasswordHash, arg.UsesDefaultCredentials, arg.CredentialsUpdatedAt)
	return err
}

const updateAdministratorUsername = `-- name: UpdateAdministratorUsername :exec
UPDATE administrators
SET username = ?, uses_default_credentials = ?,
    credentials_updated_at = ?
WHERE id = 1
`

type UpdateAdministratorUsernameParams struct {
	Username               string
	UsesDefaultCredentials int64
	CredentialsUpdatedAt   int64
}

func (q *Queries) UpdateAdministratorUsername(ctx context.Context, arg UpdateAdministratorUsernameParams) error {
	_, err := q.db.ExecContext(ctx, updateAdministratorUsername, arg.Username, arg.UsesDefaultCredentials, arg.CredentialsUpdatedAt)
	return err
}

const updateNodeHeartbeat = `-- name: UpdateNodeHeartbeat :execrows
UPDATE nodes
SET hostname = ?, agent_version = ?, operating_system = ?, architecture = ?,
    applied_configuration_revision = ?, configuration_error = ?,
    configuration_error_revision = ?, last_seen_at = ?
WHERE id = ? AND revoked_at IS NULL
`

type UpdateNodeHeartbeatParams struct {
	Hostname                     string
	AgentVersion                 string
	OperatingSystem              string
	Architecture                 string
	AppliedConfigurationRevision int64
	ConfigurationError           *string
	ConfigurationErrorRevision   *int64
	LastSeenAt                   *int64
	ID                           string
}

func (q *Queries) UpdateNodeHeartbeat(ctx context.Context, arg UpdateNodeHeartbeatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateNodeHeartbeat,
		arg.Hostname,
		arg.AgentVersion,
		arg.OperatingSystem,
		arg.Architecture,
		arg.AppliedConfigurationRevision,
		arg.ConfigurationError,
		arg.ConfigurationErrorRevision,
		arg.LastSeenAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertAgentEnrollmentKey = `-- name: UpsertAgentEnrollmentKey :exec
INSERT INTO agent_enrollment (
    id, enabled, key_digest, key_encrypted, created_at, rotated_at
) VALUES (1, 1, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    enabled = 1,
    key_digest = excluded.key_digest,
    key_encrypted = excluded.key_encrypted,
    rotated_at = excluded.rotated_at
`

type UpsertAgentEnrollmentKeyParams struct {
	KeyDigest    []byte
	KeyEncrypted []byte
	CreatedAt    int64
	RotatedAt    int64
}

func (q *Queries) UpsertAgentEnrollmentKey(ctx context.Context, arg UpsertAgentEnrollmentKeyParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgentEnrollmentKey,
		arg.KeyDigest,
		arg.KeyEncrypted,
		arg.CreatedAt,
		arg.RotatedAt,
	)
	return err
}

const upsertNodeNetworkInventory = `-- name: UpsertNodeNetworkInventory :exec
INSERT INTO node_network_inventories (
    node_id, payload, captured_at, received_at, last_error
) VALUES (?, ?, ?, ?, NULL)
ON CONFLICT (node_id) DO UPDATE SET
    payload = excluded.payload,
    captured_at = excluded.captured_at,
    received_at = excluded.received_at,
    last_error = NULL
`

type UpsertNodeNetworkInventoryParams struct {
	NodeID     string
	Payload    *string
	CapturedAt *int64
	ReceivedAt int64
}

func (q *Queries) UpsertNodeNetworkInventory(ctx context.Context, arg UpsertNodeNetworkInventoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertNodeNetworkInventory,
		arg.NodeID,
		arg.Payload,
		arg.CapturedAt,
		arg.ReceivedAt,
	)
	return err
}

const upsertNodeSyncSession = `-- name: UpsertNodeSyncSession :exec
INSERT INTO node_sync_sessions (
    node_id, session_id, requested_at, expires_at
) VALUES (?, ?, ?, ?)
ON CONFLICT (node_id) DO UPDATE SET
    session_id = excluded.session_id,
    requested_at = excluded.requested_at,
    expires_at = excluded.expires_at,
    delivered_at = NULL
`

type UpsertNodeSyncSessionParams struct {
	NodeID      string
	SessionID   string
	RequestedAt int64
	ExpiresAt   int64
}

func (q *Queries) UpsertNodeSyncSession(ctx context.Context, arg UpsertNodeSyncSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertNodeSyncSession,
		arg.NodeID,
		arg.SessionID,
		arg.RequestedAt,
		arg.ExpiresAt,
	)
	return err
}

const upsertRevokedAgentCredential = `-- name: UpsertRevokedAgentCredential :exec
INSERT INTO revoked_agent_credentials (credential_digest, revoked_at, reason)
VALUES (?, ?, ?)
ON CONFLICT (credential_digest) DO UPDATE SET
    revoked_at = excluded.revoked_at,
    reason = excluded.reason
`

type UpsertRevokedAgentCredentialParams struct {
	CredentialDigest []byte
	RevokedAt        int64
	Reason           string
}

func (q *Queries) UpsertRevokedAgentCredential(ctx context.Context, arg UpsertRevokedAgentCredentialParams) error {
	_, err := q.db.ExecContext(ctx, upsertRevokedAgentCredential, arg.CredentialDigest, arg.RevokedAt, arg.Reason)
	return err
}

const useTOTPStep = `-- name: UseTOTPStep :execrows
UPDATE administrators
SET totp_last_used_step = ?
WHERE id = 1 AND totp_enabled = 1 AND totp_last_used_step < ?
`

type UseTOTPStepParams struct {
	TotpLastUsedStep   int64
	TotpLastUsedStep_2 int64
}

func (q *Queries) UseTOTPStep(ctx context.Context, arg UseTOTPStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, useTOTPStep, arg.TotpLastUsedStep, arg.TotpLastUsedStep_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
