// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: queries.sql

package configdb

import (
	"context"
)

const createAdministrator = `-- name: CreateAdministrator :exec
INSERT INTO administrators (
    id, username, password_hash, locale, uses_default_credentials,
    created_at, credentials_updated_at
) VALUES (1, ?, ?, ?, ?, ?, ?)
`

type CreateAdministratorParams struct {
	Username               string
	PasswordHash           string
	Locale                 string
	UsesDefaultCredentials int64
	CreatedAt              int64
	CredentialsUpdatedAt   int64
}

func (q *Queries) CreateAdministrator(ctx context.Context, arg CreateAdministratorParams) error {
	_, err := q.db.ExecContext(ctx, createAdministrator,
		arg.Username,
		arg.PasswordHash,
		arg.Locale,
		arg.UsesDefaultCredentials,
		arg.CreatedAt,
		arg.CredentialsUpdatedAt,
	)
	return err
}

const createAdministratorSession = `-- name: CreateAdministratorSession :exec
INSERT INTO administrator_sessions (
    token_digest, created_at, expires_at, client_address, user_agent
) VALUES (?, ?, ?, ?, ?)
`

type CreateAdministratorSessionParams struct {
	TokenDigest   []byte
	CreatedAt     int64
	ExpiresAt     int64
	ClientAddress string
	UserAgent     string
}

func (q *Queries) CreateAdministratorSession(ctx context.Context, arg CreateAdministratorSessionParams) error {
	_, err := q.db.ExecContext(ctx, createAdministratorSession,
		arg.TokenDigest,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.ClientAddress,
		arg.UserAgent,
	)
	return err
}

const createNode = `-- name: CreateNode :exec
INSERT INTO nodes (
    id, name, hostname, credential_digest, agent_version,
    operating_system, architecture, registered_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateNodeParams struct {
	ID               string
	Name             string
	Hostname         string
	CredentialDigest []byte
	AgentVersion     string
	OperatingSystem  string
	Architecture     string
	RegisteredAt     int64
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) error {
	_, err := q.db.ExecContext(ctx, createNode,
		arg.ID,
		arg.Name,
		arg.Hostname,
		arg.CredentialDigest,
		arg.AgentVersion,
		arg.OperatingSystem,
		arg.Architecture,
		arg.RegisteredAt,
	)
	return err
}

const createNodeCapability = `-- name: CreateNodeCapability :exec
INSERT INTO node_capabilities (node_id, capability)
VALUES (?, ?)
`

type CreateNodeCapabilityParams struct {
	NodeID     string
	Capability string
}

func (q *Queries) CreateNodeCapability(ctx context.Context, arg CreateNodeCapabilityParams) error {
	_, err := q.db.ExecContext(ctx, createNodeCapability, arg.NodeID, arg.Capability)
	return err
}

const createSystemState = `-- name: CreateSystemState :exec
INSERT INTO system_state (id, history_generation)
VALUES (1, ?)
`

func (q *Queries) CreateSystemState(ctx context.Context, historyGeneration string) error {
	_, err := q.db.ExecContext(ctx, createSystemState, historyGeneration)
	return err
}

const deleteAdministratorSession = `-- name: DeleteAdministratorSession :exec
DELETE FROM administrator_sessions
WHERE token_digest = ?
`

func (q *Queries) DeleteAdministratorSession(ctx context.Context, tokenDigest []byte) error {
	_, err := q.db.ExecContext(ctx, deleteAdministratorSession, tokenDigest)
	return err
}

const deleteAllAdministratorSessions = `-- name: DeleteAllAdministratorSessions :exec
DELETE FROM administrator_sessions
`

func (q *Queries) DeleteAllAdministratorSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllAdministratorSessions)
	return err
}

const deleteExpiredAdministratorSessions = `-- name: DeleteExpiredAdministratorSessions :exec
DELETE FROM administrator_sessions
WHERE expires_at <= ?
`

func (q *Queries) DeleteExpiredAdministratorSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAdministratorSessions, expiresAt)
	return err
}

const deleteNodeCapabilities = `-- name: DeleteNodeCapabilities :exec
DELETE FROM node_capabilities
WHERE node_id = ?
`

func (q *Queries) DeleteNodeCapabilities(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, deleteNodeCapabilities, nodeID)
	return err
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE administrators
SET totp_secret_encrypted = NULL, totp_enabled = 0,
    totp_last_used_step = -1
WHERE id = 1
`

func (q *Queries) DisableTOTP(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, disableTOTP)
	return err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE administrators
SET totp_enabled = 1, totp_last_used_step = ?
WHERE id = 1 AND totp_secret_encrypted IS NOT NULL
`

func (q *Queries) EnableTOTP(ctx context.Context, totpLastUsedStep int64) error {
	_, err := q.db.ExecContext(ctx, enableTOTP, totpLastUsedStep)
	return err
}

const getAdministrator = `-- name: GetAdministrator :one
SELECT id, username, password_hash, locale, uses_default_credentials,
       totp_secret_encrypted, totp_enabled, totp_last_used_step,
       created_at, credentials_updated_at
FROM administrators
WHERE id = 1
`

func (q *Queries) GetAdministrator(ctx context.Context) (Administrator, error) {
	row := q.db.QueryRowContext(ctx, getAdministrator)
	var i Administrator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Locale,
		&i.UsesDefaultCredentials,
		&i.TotpSecretEncrypted,
		&i.TotpEnabled,
		&i.TotpLastUsedStep,
		&i.CreatedAt,
		&i.CredentialsUpdatedAt,
	)
	return i, err
}

const getAdministratorByUsername = `-- name: GetAdministratorByUsername :one
SELECT id, username, password_hash, locale, uses_default_credentials,
       totp_secret_encrypted, totp_enabled, totp_last_used_step,
       created_at, credentials_updated_at
FROM administrators
WHERE username = ? COLLATE NOCASE
`

func (q *Queries) GetAdministratorByUsername(ctx context.Context, username string) (Administrator, error) {
	row := q.db.QueryRowContext(ctx, getAdministratorByUsername, username)
	var i Administrator
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Locale,
		&i.UsesDefaultCredentials,
		&i.TotpSecretEncrypted,
		&i.TotpEnabled,
		&i.TotpLastUsedStep,
		&i.CreatedAt,
		&i.CredentialsUpdatedAt,
	)
	return i, err
}

const getAdministratorSession = `-- name: GetAdministratorSession :one
SELECT token_digest, created_at, expires_at, client_address, user_agent
FROM administrator_sessions
WHERE token_digest = ? AND expires_at > ?
`

type GetAdministratorSessionParams struct {
	TokenDigest []byte
	ExpiresAt   int64
}

func (q *Queries) GetAdministratorSession(ctx context.Context, arg GetAdministratorSessionParams) (AdministratorSession, error) {
	row := q.db.QueryRowContext(ctx, getAdministratorSession, arg.TokenDigest, arg.ExpiresAt)
	var i AdministratorSession
	err := row.Scan(
		&i.TokenDigest,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ClientAddress,
		&i.UserAgent,
	)
	return i, err
}

const getAgentEnrollment = `-- name: GetAgentEnrollment :one
SELECT id, enabled, key_digest, key_encrypted, created_at, rotated_at
FROM agent_enrollment
WHERE id = 1
`

func (q *Queries) GetAgentEnrollment(ctx context.Context) (AgentEnrollment, error) {
	row := q.db.QueryRowContext(ctx, getAgentEnrollment)
	var i AgentEnrollment
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.KeyDigest,
		&i.KeyEncrypted,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const getNodeByCredentialDigest = `-- name: GetNodeByCredentialDigest :one
SELECT id, name, hostname, credential_digest, enabled, revoked_at,
       agent_version, operating_system, architecture,
       desired_configuration_revision, applied_configuration_revision,
       configuration_error, registered_at, last_seen_at
FROM nodes
WHERE credential_digest = ?
`

func (q *Queries) GetNodeByCredentialDigest(ctx context.Context, credentialDigest []byte) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByCredentialDigest, credentialDigest)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.CredentialDigest,
		&i.Enabled,
		&i.RevokedAt,
		&i.AgentVersion,
		&i.OperatingSystem,
		&i.Architecture,
		&i.DesiredConfigurationRevision,
		&i.AppliedConfigurationRevision,
		&i.ConfigurationError,
		&i.RegisteredAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getSystemState = `-- name: GetSystemState :one
SELECT id, history_generation, pending_history_generation, history_reset_at
FROM system_state
WHERE id = 1
`

func (q *Queries) GetSystemState(ctx context.Context) (SystemState, error) {
	row := q.db.QueryRowContext(ctx, getSystemState)
	var i SystemState
	err := row.Scan(
		&i.ID,
		&i.HistoryGeneration,
		&i.PendingHistoryGeneration,
		&i.HistoryResetAt,
	)
	return i, err
}

const listNodeCapabilities = `-- name: ListNodeCapabilities :many
SELECT node_id, capability
FROM node_capabilities
ORDER BY node_id, capability
`

func (q *Queries) ListNodeCapabilities(ctx context.Context) ([]NodeCapability, error) {
	rows, err := q.db.QueryContext(ctx, listNodeCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeCapability{}
	for rows.Next() {
		var i NodeCapability
		if err := rows.Scan(&i.NodeID, &i.Capability); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, hostname, credential_digest, enabled, revoked_at,
       agent_version, operating_system, architecture,
       desired_configuration_revision, applied_configuration_revision,
       configuration_error, registered_at, last_seen_at
FROM nodes
ORDER BY name COLLATE NOCASE, id
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.CredentialDigest,
			&i.Enabled,
			&i.RevokedAt,
			&i.AgentVersion,
			&i.OperatingSystem,
			&i.Architecture,
			&i.DesiredConfigurationRevision,
			&i.AppliedConfigurationRevision,
			&i.ConfigurationError,
			&i.RegisteredAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promotePendingHistoryGeneration = `-- name: PromotePendingHistoryGeneration :execrows
UPDATE system_state
SET history_generation = pending_history_generation,
    pending_history_generation = NULL,
    history_reset_at = ?
WHERE id = 1 AND pending_history_generation = ?
`

type PromotePendingHistoryGenerationParams struct {
	HistoryResetAt           *int64
	PendingHistoryGeneration *string
}

func (q *Queries) PromotePendingHistoryGeneration(ctx context.Context, arg PromotePendingHistoryGenerationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, promotePendingHistoryGeneration, arg.HistoryResetAt, arg.PendingHistoryGeneration)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rehashAdministratorPassword = `-- name: RehashAdministratorPassword :exec
UPDATE administrators
SET password_hash = ?
WHERE id = 1
`

func (q *Queries) RehashAdministratorPassword(ctx context.Context, passwordHash string) error {
	_, err := q.db.ExecContext(ctx, rehashAdministratorPassword, passwordHash)
	return err
}

const setAgentEnrollmentEnabled = `-- name: SetAgentEnrollmentEnabled :execrows
UPDATE agent_enrollment
SET enabled = ?
WHERE id = 1
`

func (q *Queries) SetAgentEnrollmentEnabled(ctx context.Context, enabled int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, setAgentEnrollmentEnabled, enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setPendingHistoryGeneration = `-- name: SetPendingHistoryGeneration :exec
UPDATE system_state
SET pending_history_generation = ?
WHERE id = 1 AND pending_history_generation IS NULL
`

func (q *Queries) SetPendingHistoryGeneration(ctx context.Context, pendingHistoryGeneration *string) error {
	_, err := q.db.ExecContext(ctx, setPendingHistoryGeneration, pendingHistoryGeneration)
	return err
}

const setTOTPEnrollment = `-- name: SetTOTPEnrollment :exec
UPDATE administrators
SET totp_secret_encrypted = ?, totp_enabled = 0,
    totp_last_used_step = -1
WHERE id = 1
`

func (q *Queries) SetTOTPEnrollment(ctx context.Context, totpSecretEncrypted []byte) error {
	_, err := q.db.ExecContext(ctx, setTOTPEnrollment, totpSecretEncrypted)
	return err
}

const updateAdministratorLocale = `-- name: UpdateAdministratorLocale :exec
UPDATE administrators
SET locale = ?
WHERE id = 1
`

func (q *Queries) UpdateAdministratorLocale(ctx context.Context, locale string) error {
	_, err := q.db.ExecContext(ctx, updateAdministratorLocale, locale)
	return err
}

const updateAdministratorPassword = `-- name: UpdateAdministratorPassword :exec
UPDATE administrators
SET password_hash = ?, uses_default_credentials = ?,
    credentials_updated_at = ?
WHERE id = 1
`

type UpdateAdministratorPasswordParams struct {
	PasswordHash           string
	UsesDefaultCredentials int64
	CredentialsUpdatedAt   int64
}

func (q *Queries) UpdateAdministratorPassword(ctx context.Context, arg UpdateAdministratorPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateAdministratorPassword, arg.PasswordHash, arg.UsesDefaultCredentials, arg.CredentialsUpdatedAt)
	return err
}

const updateAdministratorUsername = `-- name: UpdateAdministratorUsername :exec
UPDATE administrators
SET username = ?, uses_default_credentials = ?,
    credentials_updated_at = ?
WHERE id = 1
`

type UpdateAdministratorUsernameParams struct {
	Username               string
	UsesDefaultCredentials int64
	CredentialsUpdatedAt   int64
}

func (q *Queries) UpdateAdministratorUsername(ctx context.Context, arg UpdateAdministratorUsernameParams) error {
	_, err := q.db.ExecContext(ctx, updateAdministratorUsername, arg.Username, arg.UsesDefaultCredentials, arg.CredentialsUpdatedAt)
	return err
}

const updateNodeHeartbeat = `-- name: UpdateNodeHeartbeat :execrows
UPDATE nodes
SET hostname = ?, agent_version = ?, operating_system = ?, architecture = ?,
    applied_configuration_revision = ?, configuration_error = ?, last_seen_at = ?
WHERE id = ? AND revoked_at IS NULL
`

type UpdateNodeHeartbeatParams struct {
	Hostname                     string
	AgentVersion                 string
	OperatingSystem              string
	Architecture                 string
	AppliedConfigurationRevision int64
	ConfigurationError           *string
	LastSeenAt                   *int64
	ID                           string
}

func (q *Queries) UpdateNodeHeartbeat(ctx context.Context, arg UpdateNodeHeartbeatParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateNodeHeartbeat,
		arg.Hostname,
		arg.AgentVersion,
		arg.OperatingSystem,
		arg.Architecture,
		arg.AppliedConfigurationRevision,
		arg.ConfigurationError,
		arg.LastSeenAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertAgentEnrollmentKey = `-- name: UpsertAgentEnrollmentKey :exec
INSERT INTO agent_enrollment (
    id, enabled, key_digest, key_encrypted, created_at, rotated_at
) VALUES (1, 1, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    enabled = 1,
    key_digest = excluded.key_digest,
    key_encrypted = excluded.key_encrypted,
    rotated_at = excluded.rotated_at
`

type UpsertAgentEnrollmentKeyParams struct {
	KeyDigest    []byte
	KeyEncrypted []byte
	CreatedAt    int64
	RotatedAt    int64
}

func (q *Queries) UpsertAgentEnrollmentKey(ctx context.Context, arg UpsertAgentEnrollmentKeyParams) error {
	_, err := q.db.ExecContext(ctx, upsertAgentEnrollmentKey,
		arg.KeyDigest,
		arg.KeyEncrypted,
		arg.CreatedAt,
		arg.RotatedAt,
	)
	return err
}

const useTOTPStep = `-- name: UseTOTPStep :execrows
UPDATE administrators
SET totp_last_used_step = ?
WHERE id = 1 AND totp_enabled = 1 AND totp_last_used_step < ?
`

type UseTOTPStepParams struct {
	TotpLastUsedStep   int64
	TotpLastUsedStep_2 int64
}

func (q *Queries) UseTOTPStep(ctx context.Context, arg UseTOTPStepParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, useTOTPStep, arg.TotpLastUsedStep, arg.TotpLastUsedStep_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
